### ISSUE TITLE
Haddock for Char doesn't mention all classes it instantiates 

### ISSUE THREAD

**Issue by yaitskov** [haskell/core-libraries-committee#123]
Hi,

Haddock for [Char from the latest ghc-prim](https://hackage.haskell.org/package/ghc-prim-0.9.0/docs/GHC-Types.html#t:Char) has a strange description, because it talks about applicability of `Enum` methods, though Char has instances just for Eq and Ord. Where is Show? The list on Haddock doesn't match what GHCi gives via `:i Char`

Links to enum methods and ord/chr ones give 404.

https://hackage.haskell.org/package/ghc-prim-0.9.0/docs/Data-Char.html#v:ord
https://hackage.haskell.org/package/ghc-prim-0.9.0/docs/Prelude.html#v:fromEnum

What do you think about some web crawler to verify links against 404s?

**Comment by Bodigrim** [comment]
That's because some instances of `Char` are defined in `ghc-prim` and some in `base`, but haddock comment must be shared by both of them. Users should rather refer to https://hackage.haskell.org/package/base-4.16.0.0/docs/Data-Char.html#t:Char.

That said, documentation issues or haddock infelicities are out of scope for CLC. Please raise an issue at GHC bug tracker instead.

**Comment by yaitskov** [comment]
Link to Char Haddock was generated by  HLS.

**Comment by Bodigrim** [comment]
It might be a good idea for HLS to implement a special treatment for this scenario. While normally when an entity is re-exported from several packages (as `Char` is defined in `ghc-prim` and re-exported from `base), it is better to point to the original source, here we almost never want to send users to `ghc-prim` for entities available from `base`.
