### ISSUE TITLE
Expose atomicModifyIORef2 from Data.IORef

### ISSUE THREAD

**Issue by treeowl** [haskell/core-libraries-committee#138]
`atomicModifyIORef` and `atomicModifyIORef'` are now implemented in terms of `GHC.IORef.atomicModifyIORef2`, which is in turn implemented in terms of the (relatively new) primop `atomicModifyMutVar2#`. I have been working on updating the documentation of both the existing functions to document the strict version more precisely and to reflect the small (intentional) semantic change in the lazy version that occurred when the implementation was changed. It's proving to be rather annoying to do so without being able to refer to `atomicModifyIORef2`. Additionally, `atomicModifyIORef2` is more convenient for writing certain operations, and allows those operations to be (a little) more efficient. I therefore think it should be exposed by `Data.IORef`. I have *no opinion whatsoever* about the name it should have.

The function:

```haskell
atomicModifyIORef2 :: IORef a -> (a -> (a, b)) -> IO (a, (a, b))
```

What it does, conceptually:

```haskell
atomicModifyIORef2 ref f = do
  -- Begin atomic block
  old <- readIORef ref
  let r = f old
  writeIORef ref (fst r)
  -- End atomic block
  r `seq` pure (old, r)
```

We currently expose only

```haskell
atomicModifyIORef, atomicModifyIORef' :: IORef a -> (a -> (a, b)) -> IO b
atomicModifyIORef ref f = do
  (_old, (_new, res)) <- atomicModifyIORef2 ref f
  pure res

atomicModifyIORef' ref f = do
  (_old, (_new, !res)) <- atomicModifyIORef2 ref $
    \old -> case f old of
       r@(!_new, _res) -> r
  pure res
```

With access to `atomicModifyIORef2`, users could, for example, write a version of `atomicModifyIORef` that forces the new `IORef` value but not the result value. They could also get the old value of the `IORef` directly if need be, rather than having to bundle that up in the result value.

**Comment by treeowl** [comment]
In case anyone is wondering about the ``r `seq```: without that, a series of `atomicModifyIORef` calls (in one or more threads) without someone reading and forcing the value in the `IORef` would (almost always) build a chain of thunks in the `IORef`. That was actually the old behavior of `atomicModifyIORef` (and remains the incorrectly documented behavior). But it's not something people are remotely likely to want! Forcing the result pair makes the calling thread help out, without going so far as to force the actual `IORef` contents.

**Comment by treeowl** [comment]
Another pre-emptive question: why do we return `(a, (a, b))` and not `(a, (a, b))`? The allocation of the `(a, b)` pair seems unavoidable given the mechanism by which the `atomicModifyMutVar2#` primop works, so there's no obvious efficiency benefit to unpacking the pair. Leaving it intact makes it easier to remember which one is the old `IORef` value and which is the new one.

**Comment by Bodigrim** [comment]
If it is to be exposed from `Data.IORef`, it should gain a better name than `atomicModifyIORef2`.

**Comment by treeowl** [comment]
@Bodigrim I heartily agree. Could you propose a name?

**Comment by treeowl** [comment]
Let me point out also that we don't need to stick with exactly the same type. We could have

```haskell
data Blob a b = MkBlob
  { old_val :: a
  , stuff :: Bloblet a b
  }
data Bloblet a b = MkBloblet
  { new_val :: a
  , result :: b
  }
```

**Comment by mixphix** [comment]
I think tuples (boxed or otherwise) are the simplest path forward. And that this function does not need to have `IORef` in its name. It is already in the module and type signature. It can be qualified if necessary.

If I ruled the world, I'd make a proposal to have `Data.IORef.Atomic` as such (c.f. #101), with the names intended to be imported `qualified as Atomic`:
```hs
write :: a -> IORef a -> IO ()

map :: (a -> b) -> IORef a -> IORef b

map' :: (a -> b) -> IORef a -> IORef b

modify :: (a -> (a, b)) -> IORef a -> IO b

modify' :: (a -> (a, b)) -> IORef a -> IO b

update :: (a -> (a, b)) -> IORef a -> IO (a, (a, b))

update' :: (a -> (a, b)) -> IORef a -> IO (a, (a, b))
```

**Comment by mixphix** [comment]
something like

```hs
data AtomicStrictness
  = ValueLazy a b
  | ValueStrict !a b
  | ResultStrict !a !b

update :: (a -> Atomic a b) -> IO (a, Atomic a b)
```

**Comment by treeowl** [comment]
@mixphix I don't like that, at least as is. It seems quite unlikely that many people will want the result strictness to depend on the `IORef` value. If you want something similar, I think we could do the following, but it really seems like overkill.

```haskell
data ResultStrictness
  = AllLazy
  | ValueStrict
  | ResultStrict -- Unlikely, but whatever
  | AllStrict

-- Exclude garbage with stuck types and
-- other weirdness; needed for safety.
type ProperStrictness :: ResultStrictness -> Constraint
type family ProperStrictness s where
  ProperStrictness AllLazy = ()
  ProperStrictness ValueStrict = ()
  ProperStrictness ResultStrict = ()
  ProperStrictness AllStrict = ()
  ProperStrictness x = TypeError (ShowType x :<>: 'Text " is not a valid result strictness specifier.")

type Atomic :: ResultStrictness -> Type -> Type -> Type
data family Atomic s
data instance Atomic AllLazy a b = AllLazyA a b
data instance Atomic ValueStrict a b = ValueStrictA !a b
data instance Atomic ResultStrict a b = ResultStrictA a !b
data instance Atomic AllStrict a b = AllStrictA !a !b

update :: ProperStrictness s => (a -> Atomic s a b) -> IO (a, Atomic s a b)
```

**Comment by treeowl** [comment]
@mixphix I thought about it again, and while your suggested argument order is pretty, it's not very practical. In practice, the `IORef` will almost always just be a variable name, whereas the function is likely to be a longer lambda.
 
Your `modify` functions also have inadequate types. It would be better to have

```haskell
modify :: (a -> a) -> IORef a -> IO (a, a)
modify' :: (a -> a) -> IORef a -> IO (a, a)
```

where the functions return both the old value in the `IORef` and the new one. These would both use the `atomicModifyMutVar_#` primop I forgot about until last night, which is written for just this purpose.

**Comment by Bodigrim** [comment]
> @Bodigrim I heartily agree. Could you propose a name?

I'm not good at naming, unfortunately. Dear CLC members, any ideas for a better name of `atomicModifyIORef2`?

Since we are in agreement that a better name is due, I'm labeling this as "awaiting proposal", because it is not complete unless there is a name for a function. 

Otherwise we can potentially vote to keep it `atomicModifyIORef2`, but in such case I'll be voting against, because it's not an appropriate name for a user-facing function.

**Comment by hasufell** [comment]
Suggestions:

- `atomicModifyIORefRaw`
- `atomicModifyIORefInternal`

**Comment by chshersh** [comment]
I really don't like the existing type because the lack of helpful types requires this function name to be too verbose to actually tell what it does. A proper name would be something like:

```haskell
atomicModifyIORefWithOldNewNext :: IORef a -> (a -> (a, b)) -> IO (a, (a, b))
```

I like the idea of having a separate module `Data.IORef.Atomic` because:

* It'll remove the need to have the `atomic` prefix
* It'll remove the need to have the `IORef` in name

Additionally, I would change the return type. So I personally would implement this as:

```haskell
module Data.IORef.Atomic where

data Atomic val result = Atomic
    { atomicOld :: val
    , atomicNew :: val
    , atomicNext :: result
    } 

modify :: IORef a -> (a -> a) -> IO ()

-- I would make the strict modify default as I never seen a use case for lazy one but I've seen numerous space leaks with it
modify' :: IORef a -> (a -> a) -> IO ()

modifyGet :: IORef val -> (val -> result) -> IO (Atomic val result)
```

<hr>

On a separate note, it looks like the design space for this is too huge with multiple competing and valid options.

At this point, I would recommend creating a new package like `atomic` (the name is apparently not taken, so grab it first while you can!), implement the design in there, promote the package and open a new proposal to streamline the implementation to `base` when the API stabilises.

For now, we indeed can reexport only this function from something like `GHC.IORef`, and I'd call it:

* `atomicModifyGetIORef`

**Comment by parsonsmatt** [comment]
Disagree with `Data.IORef.Atomic` - the rest of the `IORef` API having specific names is *great* for re-export and unqualified import. Changing that for a few functions would be a frustration with little benefit and could easily be done by a third party library.

I do like having a more descriptive datatype for the return value - I always get confused when writing `atomicModifyIORef` on which is which. Having a record to specify would make things easier.

**Comment by treeowl** [comment]
Let me state again that the natural result, implementation-wise, is a *nested* structure, and I don't think that's unduly unfriendly for users. I would oppose flattening the result to a single record.

**Comment by parsonsmatt** [comment]
To clarify, you're referring to this:

> Another pre-emptive question: why do we return (a, (a, b)) and not (a, a, b)? The allocation of the (a, b) pair seems unavoidable given the mechanism by which the atomicModifyMutVar2# primop works, so there's no obvious efficiency benefit to unpacking the pair. Leaving it intact makes it easier to remember which one is the old IORef value and which is the new one.

The primop returns `(a, b)`, so we might as wel have `(a, (a, b))` - we'll have to allocate the inner and outer tuple *anyway*, so might as well not bother unpacking. Is that right?

If we're allocating a whole new structure *anyway* for this, then we lose the ability to share the tuple allocation, right? So `data Outer a b = Outer a (a, b)` would be an equal amount of allocation to the `(a, (a, b))` (sharing the inner `(a, b)`), but if we had `data Outer a b = Outer a (Inner a b)`, then we're unnecessarily allocating the `Inner` constructor as well.

So, if we flatten it, then we only make one constructor allocation - `data Outer a b = Outer { old :: a, new :: a, result :: b }` - which does "waste" the tuple allocation, *but* we also only allocate one additional constructor, similar to the original.

**Comment by parsonsmatt** [comment]
Sorry if this is a dumb question: what's stopping us from having a `(# a, (# a, b #) #)` return type and avoiding tuple allocations altogether?

I think I'd *prefer* to see a named type with fields that make the intent of the different `a`s and `b` really clear, but it's easy enough to build that on top of a primitive with a tuple interface.

To clarify what I wrote above, we *definitely* must allocate the inner tuple - so that's 1 allocation. Then we need to do another allocation for the outer wrapper (unless we do the unboxed tuple) - and a 2-tuple is slightly smaller thna a 3-tuple, and we've *already* alloctaed a 2-tuple for the inner result, so just doing `(a, (a, b))` is the most memory efficient. 

We *could* have a type like:

```haskell
data AtomicModifyResult a b = AtomicModifyResult
     { old :: a
    , newAndResult :: (a, b)
    }
```

which would have the same allocation properties as `(a, (a, b))`, but with one set of named fields. So this has the same performance as the tuple implementation.

At the cost of an additional allocation, we could have:

```
data AtomicModifyResult a b = AtomicModifyResult
     { old :: a
    , newAndResult :: Inner a b
    }

data Inner a b = Inner { new :: a, result :: b }
```

Which throws away the inner tuple and repacks it in the `Inner` datatype. So now we're not getting "free" legibility, we're trading a bit of perf for legibility - and making a named type like `Inner` the result of these functions is a much more invasive breaking change (since we'd need to change the type of `atomicModifyIORef :: IORef a -> (a -> Inner a b) -> IO (Inner a b)`, which is pretty onerous).

**Comment by treeowl** [comment]
@parsonsmatt Your `inner` has exactly the same memory layout as a tuple, so there's no difficulty just using it directly—it has no additional cost. The outer tuple/record will be unboxed by the simplifier, so that's not a problem either.

**Comment by Bodigrim** [comment]
Relevant documentation: https://ghc.gitlab.haskell.org/ghc/doc/libraries/base-4.18.0.0/GHC-Exts.html#v:atomicModifyMutVar2-35-

@treeowl are you happy with `data AtomicModifyResult a b = AtomicModifyResult { old :: a, newAndResult :: Inner a b }` interface? Could you please raise an MR so that we can all be on the same page?

**Comment by Bodigrim** [comment]
@treeowl just a gentle reminder about this.

**Comment by treeowl** [comment]
I missed your previous comment. I'll raise an MR.

**Comment by treeowl** [comment]
I'll submit an MR and reopen.
