### ISSUE TITLE
Use a non-allocating (or less-allocating) implementation of atomicSwapIORef

### ISSUE THREAD

**Issue by treeowl** [haskell/core-libraries-committee#139]
`atomicSwapIORef :: IORef a -> a -> IO a` is currently implemented in terms of `atomicModifyMutVar2#`. When I wrote that implementation, I imagined that `atomicSwapIORef` would soon get its own primop using an atomic exchange operation, so I didn't worry about optimizing it too much. However, I am not competent to implement said primop, and no one else has done so in the last few years. So I think it makes sense to try to improve matters. The most annoying thing about `atomicSwapIORef` is that by using `atomicModifyMutVar2#`, it's forced to allocate two intermediate thunks, plus a `Box` (essentially `Solo`) to hold the new value. I propose that we replace it with an implementation based on `casMutVar#`:

```haskell
atomicSwapIORef :: IORef a -> a -> IO a
atomicSwapIORef (IORef (STRef ref)) new = IO (atomicSwapMutVar# ref new)

atomicSwapMutVar# :: MutVar# RealWorld a -> a -> State# RealWorld -> (# State# RealWorld, a #)
atomicSwapMutVar# ref new s1 =
  case readMutVar# ref s1 of { (# s2, old #) ->
  case casMutVar# ref old new s2 of
    -- We use 'lazy' here to guarantee that we don't force the old value before
    -- performing the CAS and try to use the forced value for the CAS. Something like
    --
    -- case old of
    --   I# old# -> let old' = I# old# in caseMutVar# ref old' new s2
    --
    -- would fail every time. I don't imagine this would ever happen anyway,
    -- but it's probably better to be safe than sorry.
    (# s3, 0#, _ #) -> (# s3, lazy old #)
    (# s3, _, _ #) ->
      -- CAS failed. We don't use the value returned by casMutVar# in this case
      -- because casMutVar# performs a check after the actual CAS
      -- operation. Although the delay that introduces is tiny, it is better to
      -- start over with a fresh readMutVar# to increase the chance of CAS
      -- success in the next attempt.
      atomicSwapMutVar# ref new s3 }
```

As it's possible that some programs rely on `atomicSwapIORef` yielding, an alternative is

```haskell
atomicSwapIORef :: IORef a -> a -> IO a
atomicSwapIORef (IORef (STRef ref)) new = yield >> IO (atomicSwapMutVar# ref new)
```

**Comment by treeowl** [comment]
I haven't checked the exact counts, but this should save at least 7 words of allocation for the non-yielding version: 3 words for the application thunk, 2 for the selector thunk, and 2 for the `Box`. The yielding version will drop the savings to 6 words. Excessive allocation is generally bad for concurrency, since GC stops the world.

**Comment by treeowl** [comment]
Does no one have an opinion on whether this function should yield implicitly? I don't know if that's needed for backwards compatibility or not.

**Comment by Kleidukos** [comment]
We should probably wait for the core GHC developers to finish this semester's releases and ask their opinion on this.

**Comment by Bodigrim** [comment]
@treeowl "yielding" = "giving way to GC"?

**Comment by parsonsmatt** [comment]
[`yield` docs](https://www.stackage.org/haddock/lts-20.13/base-4.16.4.0/Control-Concurrent.html#v:yield). The two ways I can see that mattering are a) asynchronous exception delivery and b) thread switching in a low CPU environment.

I may be really mistaken, but the failure case for asynchronous exceptions is something like: you'd have to have a *very* tight loop - no allocations at all - with `atomicSwapIORef` being the only call that currently allows an async exception to be delivered. *Then*, you need to depend on thta behavior, and *expect* that code to be killed in a timely manner by an async exception. This scenario seems unlikely enough that I wouldn't worry about it, and I can't conjure up any other scenarios where async exceptions may matter for it.

For allowing/forcing a context switch, this feels *more* likely, but we're still dealing with "undocumented and possibly surprising behavior of the function." The problem scenario here, as I understand it, is if a programmer writes a loop that only has a single `yield` point now in `atomicSwapIORef`. They're only running a single capability, or are using the non-threaded runtime. And then finally, they *depend* on allowing the thread to context switch, so other threads can run. The combination of "Depends on multithreaded behavior" and "Running few enough capabilities to trigger the issue" to me points to either a very poor understanding of Haskell, *or* a very sophisticated one, and they're most likely calling `yield` *already* because nothing in `atomicSwapIORef` indicates that it does that.

 If `yield` isn't free, then I think we should probably err on the side of calling it less often, and omitting from this implementation. How does the `yield` call have an additional allocation? Is that from `>>`?

**Comment by Bodigrim** [comment]
It is not a part of the written contract of `atomicSwapIORef` that it gives a moment for thread switch. If users need to yield, they should call `yield` directly. I believe that `atomicSwapIORef` should be as fast and non-allocating as possible.

**Comment by treeowl** [comment]
@parsonsmatt My rather vague recollection is that `yield#` works by allocating a word (since the allocator yields). But it's quite possible that's changed since I last read about it, if I even got that right to begin with.

**Comment by Bodigrim** [comment]
Trying to evaluate this, I'm stuck with the description of [`atomicModifyMutVar2#`](https://hackage.haskell.org/package/ghc-prim-0.8.0/docs/GHC-Prim.html#v:atomicModifyMutVar2-35-):

> `atomicModifyMutVar2# :: MutVar# s a -> (a -> c) -> State# s -> (# State# s, a, c #) `
> Modify the contents of a `MutVar#`, returning the previous contents and the result of applying the given function to the previous contents. Note that this isn't strictly speaking the correct type for this function; it should really be `MutVar# s a -> (a -> (a,b)) -> State# s -> (# State# s, a, (a, b) #)`, but we don't know about pairs here.

And yet the current implementation of `atomicSwapIORef` is 

```haskell
atomicSwapIORef (IORef (STRef ref)) new = IO $ \s ->
  case atomicModifyMutVar2# ref (\_old -> Box new) s of
    (# s', old, Box _new #) -> (# s', old #)
```

where the argument of `atomicModifyMutVar2#` clearly is not of form `a -> (a, b)`. Is the comment obsolete?

----

> The most annoying thing about `atomicSwapIORef` is that by using `atomicModifyMutVar2#`, it's forced to allocate two intermediate thunks, plus a `Box` (essentially `Solo`) to hold the new value. 

Please elaborate in the proposal, explaining which two thunks we are talking about. Maybe show relevant Core?

**Comment by treeowl** [comment]
@Bodigrim , the comment is not out of date, but rather an intentional simplifying lie (and not my lie; someone higher up made that call). `atomicModifyMutVar2#` actually works with records other than pairs; the new value installed in the `MutVar#` is the first field in the result that is represented by a pointer. This only works correctly if said field has a type of kind `Type` (i.e., a lifted type) which is not unpacked. The current implementation of `atomicSwapMutVar#` uses `Box` (a copy of `Solo` from before that existed) as the record type. That was a very simple way to save one word of allocation.

**Comment by treeowl** [comment]
@Bodigrim The two thunks don't appear in Core. They're created in the Cmm implementation of the primop. One thunk represents `res = (\ _old -> Box new) old`, while the other represents `fst res`.

**Comment by Bodigrim** [comment]
To be honest, I don't really have any intuition in this area. Any chance to benchmark the existing implementation vs. the proposal?

**Comment by treeowl** [comment]
@Bodigrim, here's a simple informal benchmark, in which two threads each call `atomicSwapIORef` a fixed number of times on the same `IORef`.

```haskell
{-# language BangPatterns #-}
{-# language LambdaCase #-}
module Main where
import Data.IORef
import qualified GHC.IORef as Old
import qualified AtomicSwap as New
import System.Environment
import Control.Concurrent.Async
import System.Exit

oldBumper :: Int -> Int -> IORef Int -> IO ()
oldBumper !counter !n !ref
  | n == 0
  = print counter
  | otherwise
  = do
      old <- Old.atomicSwapIORef ref n
      oldBumper (counter + old) (n - 1) ref

newBumper :: Int -> Int -> IORef Int -> IO ()
newBumper !counter !n !ref
  | n == 0
  = print counter
  | otherwise
  = do
      old <- New.atomicSwapIORef ref n
      newBumper (counter + old) (n - 1) ref

main :: IO ()
main = do
  bumper <- getArgs >>= \case
    ["old"] -> pure oldBumper
    ["new"] -> pure newBumper
    _ -> die "Expected a single argument of either \"old\" or \"new\"."
  ref <- newIORef 3
  withAsync (bumper 0 100000000 ref) $ \a -> do
    bumper 0 100000000 ref
    wait a
```

On my system, if I compile with the threaded runtime, running the executable with an argument of `old` (and `+RTS -N2` or `+RTS -N3`) takes about 17.5 to 20 seconds, while running it with an argument of `new` takes around 13.5 to 15 seconds. It's not a huge improvement, but it's a consistent improvement.

Note: I just realized we still don't actually expose `atomicSwapIORef` through `Data.IORef`; we really should. It is currently used to implement `Data.IORef.atomicWriteIORef`, `GHC.Conc.Posix.{prodServiceThread, service_loop, service_cont}`, `GHC.Event.Control.closeControl`, and `GHC.ForeignPtr.foreignPtrFinalizer`. Should exposing it through `Data.IORef` be discussed in this issue, or in a new one?

**Comment by Bodigrim** [comment]
> Should exposing it through `Data.IORef` be discussed in this issue, or in a new one?

A separate issue please. Also see #101 for other API improvements.

**Comment by Bodigrim** [comment]
@treeowl could you possibly engage some reviewers with the experience in this area? I'm not sure who of GHC developers is the most acquainted with it.

**Comment by treeowl** [comment]
@Bodigrim , I don't know either. Maybe @bgamari or @rrnewton can advise, or suggest a reviewer.

**Comment by treeowl** [comment]
Or maybe @Kleidukos could point in the right direction?

**Comment by Kleidukos** [comment]
If I was to take performance advice I'd certainly take it from @kozross and @doyougnu :)

**Comment by bgamari** [comment]
If the problem is the lack of a atomic-exchange based `atomicSwapMutVar#` then I think it would be preferable to just fix that than add a CAS-based approach. It would be quite straightforward to implement.

**Comment by doyougnu** [comment]
FYI in case anyone stumbles upon this thread in the future. The steps to add a primop fairly straightforward, see [this](https://gitlab.haskell.org/ghc/ghc/-/issues/10809#note_399428) comment and [this](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/7245) merge request which I'll get back to at some point.

**Comment by Bodigrim** [comment]
@treeowl shall we put changes to `GHC.IORef` from https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10132/diffs for a vote instead of your original proposal?

**Comment by treeowl** [comment]
Yes please! Would someone properly set up for GHC development be able to give some perf info?

**Comment by treeowl** [comment]
@Bodigrim Let's not worry about benchmarks actually. @bgamari's version is just obviously a better way if there's contention, and should be at least as good the rest of the time. Please put this to a vote.

**Comment by Bodigrim** [comment]
Dear CLC members, 

Current implementation of [`GHC.IORef.atomicSwapIORef`](https://hackage.haskell.org/package/base-4.18.0.0/docs/GHC-IORef.html#v:atomicSwapIORef) is:
```haskell
atomicSwapIORef :: IORef a -> a -> IO a
-- Bad implementation! This will be a primop shortly.
atomicSwapIORef (IORef (STRef ref)) new = IO $ \s ->
  case atomicModifyMutVar2# ref (\_old -> Box new) s of
    (# s', old, Box _new #) -> (# s', old #)
```

The routine we employ here, [`atomicModifyMutVar2#`](https://ghc.gitlab.haskell.org/ghc/doc/libraries/ghc-prim-0.10.0/GHC-Prim.html#v:atomicModifyMutVar2-35-) is very expensive, allocating two intermediate thunks. But it's crucial for atomic primops to be fast, otherwise they lock things and build up contention.

In https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10132/diffs @bgamari acts on the comment and introduces an efficiently-implemented primop `atomicSwapMutVar#`. The only part of the MR which falls under CLC purview is that it changes `atomicSwapIORef` to be a simple wrapper:
```haskell
atomicSwapIORef :: IORef a -> a -> IO a
atomicSwapIORef (IORef (STRef ref)) new = IO $ \s ->
  case atomicSwapMutVar# ref new s of
    (# s', old #) -> (# s', old #)
```

Let's vote on this change to `atomicSwapIORef`.

@tomjaguarpaw @chshersh @mixphix @angerman @parsonsmatt @hasufell 

----

+1 from me. If we have a dedicated primop, it would be stupid not to employ it.

**Comment by chshersh** [comment]
+1

**Comment by mixphix** [comment]
+1

**Comment by tomjaguarpaw** [comment]
+1

**Comment by Bodigrim** [comment]
@hasufell @angerman @parsonsmatt just a gentle reminder to vote.

**Comment by hasufell** [comment]
I trust Ben to know what he's doing, so +1.

**Comment by Bodigrim** [comment]
Thanks all, 5 votes in favour out of 7 are enough to approve.
