### ISSUE TITLE
Update and expand atomic modification Haddocks

### ISSUE THREAD

**Issue by treeowl** [haskell/core-libraries-committee#140]
The documentation for `atomicModifyIORef` and `atomicModifyIORef'` are insufficient to allow users to form an accurate mental model of what they do, and therefore of what must be taken into account what using them. I'd like to expand it. Additionally, the documentation for `atomicModifyIORef` is out of date (incorrect), and needs to be updated.

While we're at it, there's a lazy pattern match in the definition of `atomicModifyIORef` that does nothing—the pair it pretends to defer matching on is already forced by `atomicModifyIORef2`, so the lazy match is purely confusing. Let's remove it.

[The GHC MR](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10048)

**Comment by hasufell** [comment]
Afaiu documentation changes are not governed by CLC, so I suggest to split the PR?

**Comment by treeowl** [comment]
@hasufell as soon as I get confirmation. I don't want to churn too much. Are changes that affect literally nothing subject to CLC approval? That's what the lazy pattern thing is. I don't know the rules these days.

**Comment by hasufell** [comment]
Since performance falls in our ballpark, I think it's at least good to raise it and see if anyone disagrees with your assessment.

**Comment by chshersh** [comment]
@treeowl as @hasufell correctly noticed, the PR in question doesn't only change documentation but also changes the implementation w.r.t. to laziness. All visible changes are subject to CLC vote.

However, if you can prove that your PR doesn't have any visible changes then you don't need a CLC vote for this 👍🏻 

I checked the code for `atomicModifyIORef2` and after a quick look it indeed feels like `~` is redundant. But this is not my area of expertise. I probably would try to confirm this expectation with microbenchmarks or profiler to see allocated memory or by looking at core.

You can also ask feedback from more people to be more confident in these changes. At this stage, CLC can be an independent group of experts to assess whether there're any visible changes or not.

<hr>

On a separate note, @treeowl, I noticed that you currently have **10** open CLC proposals (out of 29 total) with some of the proposals still waiting for your actions. Old proposals are not closing while the new ones continue being created.

I understand that you're passionate about Haskell and really want to make it a better place and that you also probably do all this work for free in your personal time.

But so does CLC. Prioritizing and spending our own free time and providing valuable feedback across many proposals is more difficult than across few, and will incur higher delays in the CLC response.

We don't have a policy about how many in-flight proposals a single person can have (and probably we won't ever have such a policy). But I urge you to be more empathetic to the free time of CLC members and prioritize making progress on your already open proposals instead of constantly creating new ones.

I would like to add that I'm expressing my personal opinion and preference here as a CLC member and not an official position of CLC, so opinions of other people may differ.  I joined CLC only a couple of weeks ago and there's already 29 proposals I need to thoroughly review and provide feedback. So having more proposals means having higher delays in providing feedback from my side which may disrupt CLC workflow.

I also don't want you to discourage from proposing improvements to `base`. So as a quick and dirty solution I can propose to mark your proposals with `Status: Draft` if you want to use the CLC issue tracker as a place for your personal ideas of improvements to collect feedback from the wider Haskell community while not disrupting the CLC work.

P.S. Apologies if some of my words or phrases sound too rude. As an autistic non-native English speaker, I sometimes find it hard to express my feelings precisely. We both want to make Haskell better, so I appreciate if you would understand where I'm coming from and how I personally think we could collaborate better 🤗

**Comment by hasufell** [comment]
I also want to express that I appreciate the engagement of @treeowl and other contributors and that I see the CLC tracker not only as a starting point for proposals, but also as a way to generally source opinions.

Maybe we can make a better distinction somehow, so that CLC members are able to prioritize better.

**Comment by treeowl** [comment]
@chshersh I've closed one of my open issues, and moved two of them along (one toward acceptance and one toward likely closure). I wasn't sure how many issues to open about atomic modification primops, since there are several unrelated issues affecting the same small set of functions. These are all in a sense cleanups/follow-ups following up on changes I made several years ago. I will check the Core for the two implementations here. Does the CLC want to weigh in on the documentation changes?

**Comment by treeowl** [comment]
I compiled the old and new definitions using `-ddump-simpl -dsuppress-uniques` and GHC 9.6, with both `-O1` and `-O2`, and diffed the resulting Core. They were absolutely identical: no difference in code, unfolding, demand signature, inlining guidance, etc. So there shouldn't be any difference in performance or laziness whatsoever.

**Comment by Bodigrim** [comment]
Thanks, @treeowl. I took a look myself and I agree that 
```diff
-  (_old, ~(_new, res)) <- atomicModifyIORef2 ref f
+  (_old, (_new, res)) <- atomicModifyIORef2 ref f
```
does not matter because 
```haskell
atomicModifyIORef2 :: IORef a -> (a -> (a,b)) -> IO (a, (a, b))
atomicModifyIORef2 ref f = do
  r@(_old, (_new, _res)) <- atomicModifyIORef2Lazy ref f
  return r
```
does force the pair inside anyway. And `atomicModifyIORef2` cannot become lazier any time soon because `atomicModifyIORef2Lazy` builds nested tuples from an unboxed 3-tuple.

Unless someone disagrees within 7 days, you can proceed with the MR. In the future, however, please do not bundle documentation changes with non-documentation to save time of everyone.

**Comment by treeowl** [comment]
@Bodigrim Do you think you could comment on the MR to indicate that the CLC has no objections to this change?

**Comment by Bodigrim** [comment]
Done.

Closing, marking as "approved" in the sense "approved that no approval needed".

**Comment by chshersh** [comment]
I'm trying to summarise the state of this proposal as part of my volunteering effort to track the progress of all `approved` CLC proposals.

> This ticket is in a weird state because it originally was opened as a potential visible change but turned out to be documentation + non-observable change. I'll remove the `approved` label and leave only `out-of-scope`. I believe, it's fine to have some discussion and keep the issue as `out-of-scope`. Still, I'll provide my usual report message for stats and accountability.

| Field | Value |
|---|---|
| **Authors**            |  @treeowl   |
| **Status**             |  merged  |
| **`base` version**     | `4.19.0.0`  |
| **Merge Request (MR)** | https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10048 |
| **Blocked by**         | nothing |
| **CHANGELOG entry**    | not needed  |
| **Migration guide**    |  not needed |

[changelog]: https://gitlab.haskell.org/ghc/ghc/-/blob/master/libraries/base/changelog.md

Please, let me know if you find any mistakes 🙂
