### ISSUE TITLE
Data.Data.Data instance for lists is different from derived ones

### ISSUE THREAD

**Issue by treeowl** [haskell/core-libraries-committee#147]
I noticed that we have

```haskell
nilConstr :: Constr
nilConstr    = mkConstr listDataType "[]" [] Prefix
consConstr :: Constr
consConstr   = mkConstr listDataType "(:)" [] Infix
listDataType :: DataType
listDataType = mkDataType "Prelude.[]" [nilConstr,consConstr]

instance Data a => Data [a] where
  ...
  toConstr []    = nilConstr
  toConstr (_:_) = consConstr
  ...
  dataTypeOf _ = listDataType
  ...
```

The weird bit is

```haskell
consConstr   = mkConstr listDataType "(:)" [] Infix
```

If you *derive* `Data` for a type with an infix constructor,

```haskell
data Foo a = a :< Foo a
  deriving Data
```

then `-ddump-deriv` shows something like this:

```haskell
  $c:<_a1dC
    = Data.Data.mkConstrTag $tFoo_a1dB ":<" 1 [] Data.Data.Infix
```

Note that the name of the `(:)` constructor is parenthesized, while the name of the `(:<)` constructor is not. I see three reasonable ways to proceed:

1. Change the list `Constr` to remove the parentheses.
2. Change `Data` deriving to add parentheses.
3. Leave both things as they are, but document this peculiarity of the `Data [a]` instance.

**Comment by treeowl** [comment]
To be clear, I am proposing only that one of the three paths above be taken. I do not have a strong opinion about which.

**Comment by treeowl** [comment]
While we're at it, though ... I imagine we should use `mkConstrTag` instead of `mkConstr` so the list `Constr`s will be static data rather than CAFs.

**Comment by hasufell** [comment]
Am leaning towards 3.

**Comment by treeowl** [comment]
@RyanGlScott , I have the vague recollection that you may have done some work that might have run into this in some way. Your thoughts would be appreciated.

**Comment by RyanGlScott** [comment]
Most things in GHC that represent infix names as strings adhere to the convention of omitting parentheses. Aside from derived `Data` instances, derived implementations of [`conName`](https://hackage.haskell.org/package/base-4.18.0.0/docs/GHC-Generics.html#v:conName) in `Generic` instances and quoted Template Haskell names also have this property. Because of this, I would pick (1) if I were to redesign `Data` from scratch. There is existing code out there that relies on the string `"(:)"` being used, however. (One example can be found [here](https://gitlab.haskell.org/ghc/ghc/-/blob/73d07c6e1986bd2b3516d4f009cc1e30ba804f06/libraries/template-haskell/Language/Haskell/TH/Syntax.hs#L1417-1421).)

That being said, I'm not sure that changing the `"(:)"` to `":"` would buy us that much. I don't think `Data.Data` makes any guarantees about the precise format in which the names of `Constr`s and `DataType`s will take on, and many `Data` instances in the wild pick conventions that differ from what derived `Data` instances would give you. The `(:)` data constructor is only one such exception to the rule (if there even are any rules to begin with).

**Comment by Bodigrim** [comment]
Unless there is a tangible benefit in (1), which I cannot foresee, I'd suggest sticking to (3). Documentation changes of this sort do not require CLC approval.

**Comment by chshersh** [comment]
I'm also for the option (3) - only the documentation change.
And moreover, I'm always for improving the documentation 👍🏻

**Comment by Bodigrim** [comment]
@treeowl if you are happy to proceed with (3) we can close this.

**Comment by treeowl** [comment]
Yep, I'm fine with that.
