### ISSUE TITLE
Extend Data.Bitraversable API with firstA and secondA

### ISSUE THREAD

**Issue by googleson78** [haskell/core-libraries-committee#172]
I would like to add these two functions to `Data.Bitraversable`:

```haskell

firstA :: forall t f a b c. Bitraversable t => Applicative f => (a -> f c) -> t a b -> f (t c b)
firstA f = bitraverse f pure

secondA :: forall t f a b c. Bitraversable t => Applicative f => (b -> f c) -> t a b -> f (t a c)
secondA f = bitraverse pure f
```

The motivation here is as follows:
1. In my experience, in app code, wanting to only act based on one part of a `Bitraversable` (most commonly `Either`) is more common than wanting to act on both via `bitraverse`
2. `Data.Bifunctor` which is the "parent" of `Data.Bitraversable` contains the specialised functions `first` and `second` which only map the left and the right arguments of the `Bifunctor`, and it seems like a slight inconsistency to not have them here as well.
3. I think these functions are a really safe bet, in that I think that there is not much danger of a new proposal coming later down the line suggesting breaking changes to these functions.
    This is due to the fact that I **think** there are not many opinions or different paths that can be taken on how these functions 
    should look, hence adding these functions is not a matter of pinning down which API is the most convenient/general/etc, but 
    rather a matter of filling in something that has only one possible type signature and name.
    Here are my thoughts on why the type signatures and names for these functions are predetermined:
    1. The type signatures of these functions can't really vary. This is IMO already pinned down by the correspondence between 
    2. `fmap` and `traverse`, as well as the correspondence between `bimap` and `first`+`second`.
    3. Their naming can't vary that much as well, for the sake of consistency with `bimap` and `first`+`second`, as well as the `-A` 
    suffix convention.

2\. is also the motivation for their naming, combined with the convention that an `A` suffix means "the same function but in an `Applicative` context".

There's also the question of whether we might want these two functions to be class methods of `Bitraversable`, but the committee seems to be sceptical on the value gained from some hypothetical performance gains which might be had from allowing more specific implementations of these functions. Moreover, we can more easily convert functions -> class methods, than class methods -> functions, if we ever decide that it would be beneficial

An "exact" Hackage search for these identifiers does not seem to bring up many occurrences, so breakage should be extremely limited or non-existent:
* https://hackage-search.serokell.io/?q=%5CbfirstA%5Cb - two occurrences, they do something completely different it seems
* https://hackage-search.serokell.io/?q=%5CbsecondA%5Cb - no occurrences.

**Comment by mixphix** [comment]
This doesn't pass the Fairbairn threshold, for me. It's the type of thing that belongs in a Utils module.

**Comment by googleson78** [comment]
I also want to add another point that is personally a big point for me (I'll also add it to the OP for completeness sake):

After applying @phadej's suggestion on converting these to class functions, I **think** there are not many opinions or different paths that can be taken on how these functions should look, hence adding these functions is not a matter of pinning down which API is the most convenient/general/etc, but rather a matter of filling in a hole in a puzzle with the only possible piece that could go in that particular hole.

Here are my thoughts on why the type signatures and names for these functions are predetermined:

0. The type signatures of these functions can't really vary. This is IMO already pinned down by the correspondence between `fmap` and `traverse`, as well as the correspondence between `bimap` and `first`+`second`.
1. Their naming can't vary that much as well, for the sake of consistency with `bimap` and `first`+`second`, as well as the `-A` prefix convention.
2. Their default implementation is clear as well, and making them class members of `Bitraversable` allows for freedom for any users who want to do other things with their implementation to do so.

**Comment by endgame** [comment]
Observation: if the `-A` suffix was consistently applied, `bitraverse` would be `bimapA`.

Bikeshed: Should the functions be `traverseFirst` and `traverseSecond`? (Apart from the fact that the latter shouldn't need exist, because of the quantified superclass which ought to be added.)

**Comment by tomjaguarpaw** [comment]
> Observation: if the `-A` suffix was consistently applied, `bitraverse` would be `bimapA`.

FWIW I think it's a historical mistake that `traverse` was not called `mapA` and I think it's a further historical mistake that `mapA` has not been subsequently introduced as a synonym.

There's a meme that floats around about how fascinating it is that "it's always `traverse`". If it was called `mapA` this fascinating observation would be seen as a triviality. `traverse` sounds mysterious; `mapA` sounds obvious.

**Comment by Jashweii** [comment]
https://github.com/haskell/core-libraries-committee/issues/172#issuecomment-1582500810
I wonder if there's any hope of rewrite rules compensating for these sorts of situations. That might be too optimistic though since you'd need at least 3 to fire in this scenario. I don't know how useful illegal instances for these are, I know at least lens uses some e.g. for Level.

**Comment by athas** [comment]
This is a +1 from me.  I've often looked for these functions, thinking that I just forgot their name, because it always seemed so *obvious* to me that they should exist.  I'm fairly sure I even tried using `firstA` in the hope it would work.

**Comment by mixphix** [comment]
Given [this detailed explanation](https://github.com/haskell/core-libraries-committee/issues/93#issuecomment-1646678482) of the laziness properties of `bitraverse`, I've come around to this proposal, including the default definitions for these functions as class methods. Should users be surprised at an implementation's behaviour, there may be more information depending on the chosen type former.

**Comment by ejconlon** [comment]
+1 from me. I often use bitraverse to “choose which traverse” to use, such as choosing to traverse the recursive branches vs the leaves of a tree. Having clear synonyms for these operations (like we do in Bifunctor) would go some way to making already difficult code a little easier to understand.

**Comment by Bodigrim** [comment]
@googleson78 could you please prepare an MR which we can vote on? 

> https://hackage-search.serokell.io/?q=%5CbfirstA%5Cb - two occurrences, they do something completely different it seems

...and they do not import `Data.Bitraversable`, thus no name clashes.

**Comment by Bodigrim** [comment]
@googleson78 if there is no progress with an MR, I'll close in two weeks as abandoned.

**Comment by googleson78** [comment]
@Bodigrim 

Sorry for the huge delay, I'll get a ghc MR up today.

**Comment by googleson78** [comment]
Here's a WIP MR which almost directly reflects the current suggestion in OP - https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11466.

The MR is WIP mostly because I would love to have some feedback on the docs, but also because I'm not sure which version to put in for `@since` and the `base` changelog.

**Comment by Bodigrim** [comment]
Dear CLC members, could you please share your (non-binding) opinions on extending `class Bitraverable` with `firstA` and `secondA` as detailed in https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11466? In case you are unhappy with such extension, would you be more content with adding `firstA` / `secondA` as regular functions, not class members?

@hasufell @tomjaguarpaw @mixphix @velveteer @parsonsmatt @angerman

**Comment by hasufell** [comment]
I don't quite see strong motivation or examples why they need to be new class methods and can't just be ordinary functions. 

What kind of non-default implementations are envisioned here? And do they really warrant cluttering the class?

**Comment by googleson78** [comment]
I personally find this to be a compelling example, being the reason I switched from ordinary functions in my original proposal to class methods - https://github.com/haskell/core-libraries-committee/issues/172#issuecomment-1582500810.

**Comment by tomjaguarpaw** [comment]
I see these are particularly useful, certainly not so useful that we should enlarge `base` for them.

The reason that bitraversals are essential over and above traversals is that they incorporate ordering between elements of two different types. `firstA` and `secondA` don't use that functionality! `secondA` really is just `traverse`. Due to type variable ordering there's no similarly convenient presentation of `firstA` that avoids wrapping in a `newtype` like [`Flip`](https://www.stackage.org/haddock/lts-21.16/bifunctors-5.5.15/Data-Bifunctor-Flip.html#t:Flip), but I really don't see why it's special enough to need its own function, let alone a class member.

I suggest that users who want an efficient function of the type of `firstA` write one by hand that is monomorphic in the container type (or equivalently define a `Traversal`). The upside of including a `firstA` method relative to that is that it will be possible to program more efficiently generically over `Bitraversable` without having to manually pass around a higher order function (or `Traversal`) for that particular operation. I'm struggling to see that as something that's important to support.

**Comment by parsonsmatt** [comment]
I find @googleson78 's example to be good evidence that `firstA` ought to be a definable class member.

It is already common practice to put 'redundant' class members where performance can be significantly enhanced. `Foldable` is littered with them, but `sconcat` and `stimes` in `Semigroup` are another example. `Applicative` has `(*>)`, `(<*)` as members, and `Functor` has `(<$)`.

**Comment by hasufell** [comment]
> It is already common practice

This has never been a good argument to me. There are many common practices that don't make sense.

I can only see that very high abstraction libraries (lens?) may benefit from more aggressively adding such functionality to classes instead of requiring modules to re-define their own top-level variant if performance really matters.

I think there needs to be more "pressure". Someone could start adding those top-level functions to a common utility package, demonstrate increased usage, gather more evidence that high-abstraction libraries need it as part of the class.

Otherwise this is one of those cases "might be nice to have", no one has a good counter-argument, but no one knows how useful it really is.

**Comment by parsonsmatt** [comment]
> There are many common practices that don't make sense.

The existence of a common practice points to a problem/strategy combination that evidently *works*. I don't think you are suggesting that having `(<$)` on `Functor` doesn't make sense, and I don't see you arguing that `stimes` or similar are Bad and should have never been added. 

I wouldn't claim that *any* common practice is necessarily good, but I was also pointing to a *specific* common practice.

> I think there needs to be more "pressure". Someone could start adding those top-level functions to a common utility package, demonstrate increased usage, gather more evidence that high-abstraction libraries need it as part of the class.

I don't think this will really work. Defining a top-level `firstA k = bitraverse k pure` runs into exactly the potential performance problem that adding it as a class member solves. Allowing a more optimized `firstA` will allow for *more* performance sensitive uses of `Bitraversable`. But right now, there's no way to use `Bitraversable` in that manner. 

We have a proposal right here along with the work required to implement it. *Someone* wants it badly enough that they're willing to go through this hoopla. The commentary from non-CLC members appears to be mostly positive. I don't see a linked community discussion, either Reddit or Discourse, but I have a hard time imagining much community objection to this.

If we want to decline a proposal that is backards compatible, has minimal maintenance burden, and solve someone's real problem, I think we need to have stronger justification than "it would only be useful for a few people." If the downsides are trivial and the work is done, I think it's fine to add something if it is only useful to a *single* person.

**Comment by hasufell** [comment]
> If we want to decline a proposal that is backards compatible, has minimal maintenance burden, and solve someone's real problem, I think we need to have stronger justification than "it would only be useful for a few people." 

I don't think that is the case. CLC does not have any such policy and members are free to have diverging opinions on how much motivation they require for breakage, removal, addition etc.

To me, class changes are more delicate than "lets add another fold variant". We've seen this [before](https://github.com/haskell/core-libraries-committee/issues/91).

So I prefer not to touch classes, unless there's really good motivation.

**Comment by parsonsmatt** [comment]
> To me, class changes are more delicate than "lets add another fold variant". We've seen this [before](https://github.com/haskell/core-libraries-committee/issues/91).

This issue is a *breaking* change, though - it explicitly forbids certain kinds of instances. Adding a new function to a class with a default is a transparently *non* breaking change.

**Comment by hasufell** [comment]
> > To me, class changes are more delicate than "lets add another fold variant". We've seen this [before](https://github.com/haskell/core-libraries-committee/issues/91).
> 
> This issue is a _breaking_ change, though - it explicitly forbids certain kinds of instances. Adding a new function to a class with a default is a transparently _non_ breaking change.

Correct. This was just an example of one controversy around how to design classes. Once added, we can't revert easily without breaking.

**Comment by rhendric** [comment]
> Once added, we can't revert easily without breaking.

That's an objection to any function being added, class member or not. I'm with @parsonsmatt in that I don't see a reason to object to this particular change more strongly just because it touches a class; can you explain a potential future problem with adding these methods that doesn't apply to adding an arbitrary library function?

**Comment by Bodigrim** [comment]
I'm in favor of adding the functions to `Data.Bitraversable`: they are useful and consistent with the rest of the API. I'm unconvinced however that potential performance gains for `Either` are worth adding them as class members. That's exactly how we ended up with 17 class members of `Foldable`.

> can you explain a potential future problem with adding these methods that doesn't apply to adding an arbitrary library function?

If future `base` removes an arbitrary function from `Foo.Bar`, it's easy to provide a compatibility package with `Foo.Bar.Compat`, re-exporting `Foo.Bar` + a legacy definition of removed function. Clients can just swap imports. Removing a class member is much more difficult: you cannot provide a compatibility package at all and clients might need to make non-local changes.

**Comment by mixphix** [comment]
I think we all remember the stir caused by removing a member of a certain class. In that case it was precisely to improve the performance by having a single-method dictionary. I require certainty that the benefits of these new members outweigh the change in representation.

**Comment by rhendric** [comment]
> change in representation

Does GHC use a more efficient representation for a class (like `Bitraversable`) that has one method but also has superclasses? (I don't think it does, based on [this note](https://gitlab.haskell.org/ghc/ghc/-/blob/ghc-9.8.1-release/compiler/GHC/Tc/TyCl/Instance.hs#L221).)

**Comment by Bodigrim** [comment]
> I want to engage with this a tiny bit: what are the reasons we'd want to remove `firstA` and `secondA`?

The burden of proof lies with proposer. Why would we add them in the first place? Just because for an artificial type, not present in `base`, one can hypothetically implement `firstA` faster than default? We might disagree, but I find this argument rather weak: there are plenty of ad-hoc polymorphic functions for which one can invent a data type allowing faster specialized implementation.

**Comment by mixphix** [comment]
That note states that they use newtypes to avoid additional indirections.
```
[...]
Why do we use this different strategy?  Because otherwise we
end up with non-inlined dictionaries that look like
    $df = $cop |> blah
which adds an extra indirection to every use, which seems stupid.  See
#4138 for an example (although the regression reported there
wasn't due to the indirection).
[...]
```
But actually the newtype thing is more useful for reflection. As mentioned [here](https://github.com/haskell/core-libraries-committee/issues/85) by @RyanGlScott ([one](https://www.schoolofhaskell.com/user/thoughtpolice/using-reflection) and [two](https://www.tweag.io/blog/2017-12-21-reflection-tutorial/)), there being a unique global newtype instance means that you get a free coercion, and can easily locally specify the behaviour you want (in the same vein as `DerivingVia`).

**Comment by rhendric** [comment]
> for an artificial type

I doubt this'll make the argument much stronger, but for the record [`Joker`](https://hackage.haskell.org/package/bifunctors-5.6.1/docs/Data-Bifunctor-Joker.html#t:Joker) is such a type that wasn't invented for this proposal.

@mixfix, I'm quite confused now. I thought you started by saying you want certainty that the benefits outweigh the cost of changing the representation of `Bitraversable` from a newtype wrapping its single method to a fat data type. I thought I was responding with my (possibly incorrect?) claim that due to its superclasses, the representation of `Bitraversable` is *already* a fat data type. And now I think you're saying that actually the newtype thing has other benefits than what are highlighted in the note I linked, which is great, but I don't see how that's relevant to the question of whether `Bitraversable` gets any of those benefits currently. What have I misunderstood?

**Comment by mixphix** [comment]
I beg your pardon, I misread your initial question and elided the "also has superclasses" part.

It seems like the final example in that same note explains the case for

```hs
class DeepSeq a => C a where
  gen :: Int -> a
```

with a superclass and a function, which I (with little familiarity of the internal workings of the GHC type checker) guess is explaining this newtype strategy on a special case, and seems to indicate that this representation is used on `C` as well as `DeepSeq`?

In any case, the utility of reflecting/reifying `Bitraversable` instances is something that I'd like more information on before voting.

**Comment by Bodigrim** [comment]
Opinions so far (please correct me if I misrepresent):
* @tomjaguarpaw is sceptical on the proposal altogether, 
* @parsonsmatt is in favor, including new class members,
* @hasufell and @mixphix are somewhat unconvinced overall and sceptical on class members,
* me in favor, but without class members. 


@angerman @velveteer what do you think?

**Comment by Bodigrim** [comment]
@googleson78 how would you like to proceed? It's up to you to make a final proposal, but if non-binding opinions are of any indication, it does not look like a proposal with new class members is going to pass.

**Comment by googleson78** [comment]
I'm not really sure how I would like to proceed here yet, but I do want to note that I just accidentally found a real world case of the "usual" `Tree leafType nodeType` example, which would indeed benefit from having specifically defined `firstA` and `secondA`, in order to avoid "excessive" traversals - https://hackage.haskell.org/package/hspec-core-2.11.7/docs/src/Test.Hspec.Core.Tree.html#Tree

**Comment by tomjaguarpaw** [comment]
Could you explain how specifically defined `firstA` and `secondA` would 'avoid "excessive" traversals' there? To save others a click, the data type is

```haskell
data Tree c a =
     Node String [Tree c a]
   | NodeWithCleanup (Maybe (String, Location)) c [Tree c a]
   | Leaf a
```

**Comment by googleson78** [comment]
And of course, I actually misread the data type and you would still have to do the exact same amount of traversal, unfortunately. There are, of course, forms of trees where you would benefit from a manually defined `firstA`/`secondA`, but this is not one of them. Sorry for the noise!

Of course, a manually defined `firstA` would still potentially be marginally better, in situations where `id` is not optimised away to be an actual noop (not sure around what actually happens in reality here), but that's a much smaller improvement compared to being able to traverse less of a data type

**Comment by Bodigrim** [comment]
@googleson78 did you make your mind?

**Comment by Bodigrim** [comment]
@googleson78 could we possibly make some progress by the end of January? Otherwise I'll close the proposal as abandoned.

**Comment by googleson78** [comment]
@Bodigrim 

Sorry for the slowness and thanks for the ping.

Is it allowed to bring the proposal up for a vote with both versions available for vote, with CLC ultimately deciding which one is preferred (if any)? If yes, I would like to do that (and will create another MR to ghc with the "ordinary functions" version)

If not, and given the feedback from CLC members, I would prefer to restructure the proposal back to the original version without the class members, as well as amend the ghc MR to reflect that..

**Comment by Bodigrim** [comment]
> Is it allowed to bring the proposal up for a vote with both versions available for vote, with CLC ultimately deciding which one is preferred (if any)?

I'd rather avoid it, multiple choice questions are difficult to process. 

> If not, and given the feedback from CLC members, I would prefer to restructure the proposal back to the original version without the class members, as well as amend the ghc MR to reflect that..

@googleson78  let's go this route. If it succeeds, we can hold another vote later on promoting functions to class members.

**Comment by Bodigrim** [comment]
@googleson78 just a reminder to update the proposal / the MR.

**Comment by googleson78** [comment]
I've updated the proposal text

**Comment by Bodigrim** [comment]
Given that the proposal includes all necessary definitions and they are trivial, I'm fine to make an exception and trigger a vote without MR at ready. If the proposal gets approved and @googleson78 does not follow up with an MR, I'm fine to raise one myself.

----

Dear CLC members, let's vote on the proposal to extend [`Data.Bitraversable`](https://hackage.haskell.org/package/base-4.19.0.0/docs/Data-Bitraversable.html) module with two more functions (not class members) `firstA f = bitraverse f pure` and `secondA f = bitraverse pure f`. The detailed motivation is presented in https://github.com/haskell/core-libraries-committee/issues/172#issue-1747675925 above. Main arguments are 1) such functions are convenient shortcuts, because applications tend to traverse by the first or by the second parameter, rarely by both at the same time, 2) such function are similar to existing [`Data.Bifunctor.first`](https://hackage.haskell.org/package/base-4.19.0.0/docs/Data-Bifunctor.html#v:first) and [`Data.Bifunctor.second`](https://hackage.haskell.org/package/base-4.19.0.0/docs/Data-Bifunctor.html#v:second).

(If this proposal passes, we will hold a separate vote on promoting `firstA` and `secondA` to class members)

@tomjaguarpaw @mixphix @hasufell @angerman @parsonsmatt @velveteer 

----

+1 from me. I agree with the motivation: I rarely need to `bitraverse` by both components at the same time, it's much more common to traverse components separately, and `firstA` is a handy abbreviation, much better than `flip bitraverse pure`. I do not think the addition is going to hurt anyone; if anything it's surprising that such functions are not there already (because they match the pattern of `Data.Bifunctor`).

**Comment by tomjaguarpaw** [comment]
-1

----

As explained in [my comment above](https://github.com/haskell/core-libraries-committee/issues/172#issuecomment-1770804584) I think users should just define `Traversal`s monomorphic in the container type. I don't see any benefit of sticking this functionality onto a type class.

**Comment by angerman** [comment]
This is pretty much a toss up for me. I don't have strong opinions either towards +1 or -1.
I think I'm leaning slightly towards +1, for the same reasons @Bodigrim outlined, and I like consistency/no surprises.
While I agree with @tomjaguarpaw and @mixphix on "you likely want to use traverse", I feel that I'd rather have that as a hlint hint rather than a missing function I might be looking for out of consistency.

Maybe we can suggest putting an argument for using Traversable into the documentation for both functions? As in educate the consumer about another approach when he's looking up the function?

weak +1 from me.

**Comment by parsonsmatt** [comment]
Big +1 - seems obviously useful and consistent, especially if promoting `firstA` as a class member. 

Suggesting people use `Traversal` from the `lens` ecosystem is a bit much when `firstA` is the obvious, simple, and straightforward thing to do.

**Comment by tomjaguarpaw** [comment]
To be clear, I'm not suggesting using the `lens` ecosystem, or any library. `Traversal` just happens to be a type synonym that captures the shape in question. I'm suggesting that if you have a `Bitraverseable` `T` you can just monomorphic `firstA` and `secondA` as

```.hs
firstAT :: Applicative f => (a -> f b) -> T a c -> f (T b c)
secondAT :: Applicative f => (a -> f b) -> T c a -> f (T c b)
```

I don't see the benefit of attaching these to a type class.

**Comment by Bodigrim** [comment]
@velveteer @hasufell just a gentle reminder to vote.

**Comment by hasufell** [comment]
I don't have such a opinion about the modified proposal. It reminds me of e.g. `either f pure` and similar patterns, which I use frequently and honestly have never defined top-level functions for.

Multiple alternatives have been proposed and there's some light disagreement about whether this belongs into Bitraversable at all, which I agree *could* be confusing.

Since those are top-level functions that can easily be provided by third party packages, I'll vote conservative until there's better motivation: so -1 from me for now.

**Comment by velveteer** [comment]
Good points have been made all around. I am empathetic to being conservative on adding new class members, but less so for new top-level functions. I think consistency in base is important.

Although I do have a question. If we accept this proposal and hypothetically the subsequent class members proposal, will the class members supersede this proposal? In other words, would we delay implementation of this proposal until we vote on the other one?

+1

**Comment by googleson78** [comment]
Right now this proposal is entirely about adding two functions and zero class members. While it is true that we could also propose shifting them to be class members in the future, it is not something that I have planned. I'm more inclined to wait and potentially first encounter a motivating and "organic" motivating example before considering the future proposal

**Comment by Bodigrim** [comment]
> Although I do have a question. If we accept this proposal and hypothetically the subsequent class members proposal, will the class members supersede this proposal?

The idea was to supersede, yes, but given how tight the vote for is even simply for adding new functions, I don’t think the proposal no introduce class members stands a chance (e. g., I’ll be voting against it). 

----

At the moment there are 4 votes in favor and 3 votes against. Unless anyone changes their opinion, I’ll pronounce results as final on Tuesday.

**Comment by Bodigrim** [comment]
Thanks all, the proposal to extend [Data.Bitraversable](https://hackage.haskell.org/package/base-4.19.0.0/docs/Data-Bitraversable.html) module with two more functions (not class members) `firstA f = bitraverse f pure` and `secondA f = bitraverse pure f` is approved. Given how tight the vote was, I imagine any futher motions be futile for now.

@googleson78 please prepare a GHC MR.

**Comment by googleson78** [comment]
@Bodigrim I finally got around to updating the [existing MR](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11466/) to match what was approved here.
