### ISSUE TITLE
Request for feedback on proposed changes to GHC.Records

### ISSUE THREAD

**Issue by adamgundry** [haskell/core-libraries-committee#194]
As part of https://github.com/ghc-proposals/ghc-proposals/pull/583 I am proposing changes to the `GHC.Records` module, which contains the implementation of the `HasField` class. In particular, I propose adding a new class `SetField`, and generalising `HasField` to permit representation polymorphism. Since these definitions are tied to GHC's implementation but also part of the exposed API of `base`, I'd like to invite the CLC to express an opinion on the proposed changes.

The proposal was written prior to the current consensus about `ghc-experimental`. Thus one particular point on which I'd appreciate CLC input is whether the new definitions belong in `GHC.Records` in `base`, or if they should be added to `ghc-experimental` instead. Had `ghc-experimental` been around at the time `GHC.Records` was introduced, it would have made sense to add the new module there. But now it would seem somewhat strange to have `base` contain the existing `HasField` class for record selection, but require use of `ghc-experimental` in order to get access to `SetField` for updates.

**Comment by Bodigrim** [comment]
> But now it would seem somewhat strange to have `base` contain the existing `HasField` class for record selection, but require use of `ghc-experimental` in order to get access to `SetField` for updates.

I think it's the right thing to do: `base` continues providing `GHC.Records` with `class HasField` (which by now is somewhat stable part of the interface), and  `ghc-experimental` gains `GHC.Records.Experimental`, which re-exports `class HasField` from `base` and additionally provides an experimental `class SetField`.

**Comment by adamgundry** [comment]
Thanks, I've amended the proposal to put the new definitions in a new module in `ghc-experimental`. Thus the only change to `base` remaining in this proposal is the generalisation of `HasField` to support representation polymorphism. Does that seem reasonable to the CLC?

**Comment by Bodigrim** [comment]
@adamgundry does the generalization to unlifted types involve a change to `base` source code? How would it look like?

**Comment by adamgundry** [comment]
@Bodigrim The change is the addition of a kind signature to the `HasField` class in `GHC.Records`. The current definition is:
```hs
--   HasField :: forall {k}. k -> * -> * -> Constraint
--   getField :: forall {k} (x::k) r a. HasField x r a => r -> a
class HasField x r a | x r -> a where
  getField :: r -> a
```
And the proposed new kind signature is:
```hs
type HasField :: forall {k} {r_rep} {a_rep} . k -> TYPE r_rep -> TYPE a_rep -> Constraint
```
which also has the effect of generalising the type of `getField` to
```hs
getField :: forall {k} {r_rep} {a_rep} (x :: k) (r :: TYPE r_rep)(a :: TYPE a_rep) . HasField x r a => r -> a
```

 [Section 2 of the proposal](https://github.com/adamgundry/ghc-proposals/blob/hasfield-redesign/proposals/0000-hasfield-redesign.rst#proposed-change-specification) includes the precise new definition of the module, [section 3.3](https://github.com/adamgundry/ghc-proposals/blob/hasfield-redesign/proposals/0000-hasfield-redesign.rst#representation-polymorphism) has examples of what this enables and [section 7.9](https://github.com/adamgundry/ghc-proposals/blob/hasfield-redesign/proposals/0000-hasfield-redesign.rst#id18) has motivation and discussion of these specific changes.

**Comment by Bodigrim** [comment]
So since [`* = Type = TYPE LiftedRep`](https://hackage.haskell.org/package/base-4.18.0.0/docs/Data-Kind.html#t:Type), the current definition is effectively 
```haskell
type HasField :: k -> TYPE LiftedRep -> TYPE LiftedRep -> Constraint
class HasField x r a
```
and the new definition generalizes it to 
```haskell
type HasField :: k -> TYPE r_rep -> TYPE a_rep -> Constraint
class HasField x r a
```

----

Dear CLC members, let's vote on the proposal to generalize representations of `r` and `a` in [`class HasField x r a`](https://hackage.haskell.org/package/base-4.18.0.0/docs/GHC-Records.html#t:HasField) from `TYPE LiftedRep` to representation-polymorphic `TYPE rep`. This is not a breaking change. 

@chshersh @tomjaguarpaw @mixphix @parsonsmatt @angerman @hasufell 

----

+1 from me, the original definition restrained to `LiftedRep` seems to be an inadverent mistake in the first place.

**Comment by parsonsmatt** [comment]
+1! Looks awesome

**Comment by angerman** [comment]
Do we have an impact assessment on what this potentially break?

I'm not quite show if and how this could break, but maybe someone can either refute this concern or come up with an example that breaks due to the change in signature?

I'm tentatively supportive of this proposal, but I'd like to make sure we all considered whether or not this is potentially breaking existing code.

**Comment by hasufell** [comment]
I'm guessing we consider this module internal and don't require any impact assessment?

**Comment by adamgundry** [comment]
> Do we have an impact assessment on what this potentially break?
> 
> I'm not quite show if and how this could break, but maybe someone can either refute this concern or come up with an example that breaks due to the change in signature?
> 
> I'm tentatively supportive of this proposal, but I'd like to make sure we all considered whether or not this is potentially breaking existing code.

While this does introduce more polymorphism, GHC will default any unsolved `RuntimeRep` variables to `LiftedRep` and hence in almost all cases existing code will compile unchanged. (And moreover GHC will by default present types to users that hide the additional complexity of the `RuntimeRep`s.)

However I thought about this some more, and managed to construct an example that this change would break by exploiting the interaction between defaulting and incoherent instances. This is a very obscure corner, however. I would be surprised if any code in the wild is affected by this change.
```hs
class C rep where
  v :: forall (a :: TYPE rep) . a -> a

instance C LiftedRep where
  v x = x

instance {-# INCOHERENT #-}  rep ~ UnliftedRep => C rep where
  v x = x

-- inferred type: f :: forall {a1} {a2}. HasField "x" a1 a2 => a1 -> a1
-- but under the proposal the inferred type changes to:
-- f :: forall {a1 :: UnliftedType} {a2}. HasField "x" a1 a2 => a1 -> a1
-- (breakage occurs only if there is no top-level type signature)
f r = let _ = getField @"x" r in v r

data T = MkT { x :: T }
g = f MkT -- accepted with the first inferred type but rejected with the second
```

**Comment by simonpj** [comment]
> Do we have an impact assessment on what this potentially break?

Ideally we'd compile Hackage with the change. But that requires it to be implemented, which is in turn gated on the committee accepting it.

I agree that the imact is likely to be slight, but we could accept subject to a light review when the impact is known.  (Expected outcome = fine; ulikely outcome = wow, this broke far more than we expected, let's just think if that is unavoidable.)

**Comment by hasufell** [comment]
> But that requires it to be implemented, which is in turn gated on the committee accepting it.

Proper CLC votes require an implementation.

So I'm confused what is the process. Is this an informal vote so GHC SC can go ahead and we vote on an actual implementation a second time?

Or do we exempt this from needing an implementation, because it's part of the moral GHC internals?

**Comment by simonpj** [comment]
> So I'm confused what is the process. Is this an informal vote so GHC SC can go ahead and we vote on an actual implementation a second time?

I think this is covered (to some degree at least) by [Section 6.2 of the "GHC base library" proposal](https://github.com/haskellfoundation/tech-proposals/blob/main/proposals/accepted/051-ghc-base-libraries.rst#62ghc-proposals-process).  That is:
* At this stage the CLC is being consulted about a proposed change arising from a GHC Proposal, being evaluated by the GHC Steering Committee.
* Since the full details (incl perf and impact study) aren't available -- a proposal seldom comes with a full implementation -- the CLC offers feedback, possibly aided by a non-binding vote.
* The same is true of the GHC Steering Committee.  All proposals are accepted subject to the implementation not turning up any unexpected surprises (horribly difficult implementation, unexpectedly large impact).
* When an implementation is made, the implementor makes a fully precise CLC proposal.  But at that stage we expect the proposal to be accepted, unless there are unexpected surprises, like an unexpectely large impact.  If there are any issues of principle, we'd hope that the CLC would highlight them in the earlier consultation stage -- the one in which we are now engaged.

Does that make sense?

PS: in my previous post when I said "we" I thought I was replying to a GHC Proposal thread.  But this is actually a CLC thread, and I'm not a CLC member; my apologies.

**Comment by hasufell** [comment]
> the CLC offers feedback, possibly aided by a non-binding vote.

Right. This is what I was expecting, but it wasn't clear to me from the way @Bodigrim casted the vote.

I'm fine giving +1 as a non-binding vote, but my final vote may very well change depending on the impact assessment.

**Comment by Bodigrim** [comment]
> So I'm confused what is the process. Is this an informal vote so GHC SC can go ahead and we vote on an actual implementation a second time?
> 
> Or do we exempt this from needing an implementation, because it's part of the moral GHC internals?

I meant this to be a binding vote. The only change to `base` would be the one line quoted in https://github.com/haskell/core-libraries-committee/issues/194#issuecomment-1720263976, and the rest will be outside of CLC scope, so I find it overzealous to demand a full implementation upfront. 

I find https://github.com/haskell/core-libraries-committee/issues/194#issuecomment-1720783449 contrived beyond any imagination, so I personally think that it's overzealous to treat the change as breaking. If we were to perceive it as such, an impact assessment would be due, which is impossible without a full implementation.

However now I started to doubt that I'm acting in the best interests of the proposer. @adamgundry how would you like to proceed? Shall we vote as is or wait for a full implementation?

**Comment by adamgundry** [comment]
@Bodigrim I agree with your analysis, and I'm happy for the CLC to vote on this basis.

**Comment by Bodigrim** [comment]
Dear CLC members, let's carry on with the binding vote on https://github.com/haskell/core-libraries-committee/issues/194#issuecomment-1720263976. The quoted definition of `HasField` is the only change falling under purview of CLC, and the rest will be happening in the compiler source code itself. If you ignore incoherent :P mumbo-jumbo from https://github.com/haskell/core-libraries-committee/issues/194#issuecomment-1720783449, this is not a breaking change because GHC defaults any unsolved `RuntimeRep` variables to `LiftedRep`, thus increased levity polymorphism does not demand more type annotations in the client code. 

@tomjaguarpaw @hasufell @mixphix @angerman @velveteer @parsonsmatt 

----

+1 from me, as before. This is a very minor change and I don't feel like this is a good occasion to be overzealous and demand a full implementation upfront.

**Comment by tomjaguarpaw** [comment]
+1

**Comment by hasufell** [comment]
+1

**Comment by velveteer** [comment]
+1

**Comment by mixphix** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, 5 votes are enough to approve.

@adamgundry when MR is ready, please link this discussion from a commit message and update the changelog appropriately.
