### ISSUE TITLE
Expose unit ID in info table provenance information

### ISSUE THREAD

**Issue by bgamari** [haskell/core-libraries-committee#214]
Currently `GHC.InfoProv.InfoProv` exposes module names but not the unit ID where the module lives. I propose that we fill this gap by adding the following field to `InfoProv`:
```haskell
ipUnitId :: InfoProv -> String
```

Providing this information without significantly increasing the binary size overhead of IPE information requires some refactoring of the `whereFrom#` primop, which is currently exposed by `GHC.Exts`. As this primop is not intended for use by end-users, I propose that we remove it from `GHC.Exts` as nearly all users can instead rely on the safer and more stable `GHC.InfoProv.whereFrom`.

Implementation: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11341

**Comment by hasufell** [comment]
Since this is GHC internals, +1 from me

**Comment by mpickering** [comment]
Anything that can be done to move this one forward?

**Comment by Bodigrim** [comment]
> I propose that we remove it from `GHC.Exts` as nearly all users can instead rely on the safer and more stable `GHC.InfoProv.whereFrom`.

@bgamari is this implemented in the MR? I do not see any restriction of imports from `GHC.Exts`.

But anyway +1 from me, `whereFrom#` is [unused outside of `ghc` itself](https://hackage-search.serokell.io/?q=whereFrom%23).

@tomjaguarpaw @velveteer @mixphix @angerman @parsonsmatt any more opinions?

**Comment by Bodigrim** [comment]
@bgamari @mpickering just a reminder about my question [above](https://github.com/haskell/core-libraries-committee/issues/214#issuecomment-1789817360). Clarifying it would help to move the proposal forward.

**Comment by mixphix** [comment]
I have no issue with removing this primop. +1

**Comment by bgamari** [comment]
> @bgamari is this implemented in the MR? I do not see any restriction of imports from GHC.Exts.

I have rebased the MR and implemented the import restriction.

**Comment by bgamari** [comment]
It would be great to be able to move this forward.

**Comment by Bodigrim** [comment]
There is quite a lot going on in the MR, but I imagine it would mostly fall outside of the interests of CLC members. There are two visible changes:

* The record [`GHC.InfoProv.InfoProv`](https://hackage.haskell.org/package/base-4.19.0.0/docs/GHC-InfoProv.html#t:InfoProv) is extended with a new field `ipUnitId :: String`. This is, strictly speaking, a breaking change. 
* [`GHC.Exts.whereFrom#`](https://hackage.haskell.org/package/base-4.19.0.0/docs/GHC-Exts.html#v:whereFrom-35-) is no longer exported, clients are supposed to use [`GHC.InfoProv.whereFrom`](https://hackage.haskell.org/package/base-4.19.0.0/docs/GHC-InfoProv.html#v:whereFrom). This is also a breaking change.

I seriously doubt that these breaking changes will affect anyone. I'm fine with voting in favor of the proposal, but I'm not sure other CLC members will share this opinion. If there is an interest to proceed with breaking changes the procedure requires an impact assessment.

We can make the change non-breaking:
* Provide a pattern-synonym retaining the old structure of `InfoProv`.
* Do not remove `GHC.Exts.whereFrom#` just yet, attach a deprecation warning for now.

@angerman @tomjaguarpaw @hasufell @mixphix @velveteer @parsonsmatt opinions?

**Comment by tomjaguarpaw** [comment]
Personally I'm fine with making this change without any deprecation period. I suspect only experts will be using these features, and they will have very specialised use cases. I'm confident they'll be able to deal with any breakage that arises.

That said, I'd ultimately love this functionality to be migrated out of `base` and into a package maintained by GHC HQ. It is GHC-specific and it seems like an unnecessary drag to have this tied to `base` (and therefore to GHC releases) and to have it subject to CLC approval.

**Comment by TeofilC** [comment]
FWIW I've created a [wherefrom-compat](https://hackage.haskell.org/package/wherefrom-compat) package to export a stable interface for this stuff given that there have already been quite a few breaking changes in previous releases, and to ease migration for my proposal (if it gets accepted) but also ones like this one

**Comment by simonpj** [comment]
> That said, I'd ultimately love this functionality to be migrated out of base and into a package maintained by GHC HQ. It is GHC-specific and it seems like an unnecessary drag to have this tied to base (and therefore to GHC releases) and to have it subject to CLC approval.

Does it need to be "ultimately"?  The CLC could say, today, "please put all this in `ghc-experimental`, but expose the following smaller, stabler, but less expressive API from `base`".   Why wait?

**Comment by tomjaguarpaw** [comment]
> Does it need to be "ultimately"

Indeed not, I'd love for it to happen as soon as it can. I don't have the spare cycles to push for that myself though.

>  The CLC could say, today, "please put all this in `ghc-experimental`

I've been saying that with varying degrees of success[^1][^2]. Personally I would love this deeply-GHC-coupled stuff to be out of `base`. I don't have the time or energy to oversee its removal, let alone the work required to provide a smooth transition, but I can at least keep an eye out to ensure things don't get significantly worse.

> but expose the following smaller, stabler, but less expressive API from `base`

In general that seems like the right approach, but in this specific case I'm not convinced any form of "table provenance information" belongs in `base`. I don't even know what it is! It sounds like something that is only relevant to people doing deeply magical things with the compiler, not everyday Haskell programmers. Please correct me if I'm wrong.


[^1]: https://github.com/haskell/core-libraries-committee/issues/230#issuecomment-1831976429
[^2]: https://github.com/haskell/core-libraries-committee/issues/209#issuecomment-1729920377

**Comment by bgamari** [comment]
Has there been a final decision on this?

**Comment by Bodigrim** [comment]
> Does it need to be "ultimately"? The CLC could say, today, "please put all this in `ghc-experimental`, but expose the following smaller, stabler, but less expressive API from `base`". Why wait?

We are half a year past "split base" proposal, which several GHC developers were extremely eager to `push --force` for,  yet nothing has changed in GHC HEAD. Because it proved easier to say (and advocate for) than do. 

I was deliberately slow with processing several CLC proposals here in a false hope to see some resolution to `ghc-internal` / `ghc-experimental` split so that we can suggest "please put all this in `ghc-experimental`" in good faith. This proved to be a bad decision. 

We should not assume that `ghc-experimental` is happening until it happens for real. End of digression.

----

> Has there been a final decision on this?

I'd like to hear non-binding opinions of other CLC members if they are happy to vote in favor of the proposed breaking changes. You can trigger a binding vote immediately though, if you wish so.

**Comment by bgamari** [comment]
> Do not remove `GHC.Exts.whereFrom#` just yet, attach a deprecation warning for now.

To clarify, it is hard to imagine both implementing the thrust of this change (exposing unit ID in IPE metadata) and also retaining `whereFrom#` as-is. Specifically, adding the unit ID considerably grows the size of the already-large IPE representation fairly considerably. Mitigating this required deeper refactoring which rendered the current `whereFrom#` interface unimplementable.

Concretely, the type of `whereFrom#` changed from:
```haskell
whereFrom# :: a -> State# s -> (# State# s, Addr# #)
```
to
```haskell
whereFrom# :: a -> Addr# -> State# s -> (# State# s, Int# #)
```
since the caller is now responsible for the lifecycle of the buffer.

**Comment by hasufell** [comment]
> I'd like to hear non-binding opinions of other CLC members

I'm still fine with this breaking change without deprecation period.

**Comment by TeofilC** [comment]
> If there is an interest to proceed with breaking changes the procedure requires an impact assessment.

As this is touching the same code as the stuff on my issue, the impact assessment I did for it should also be helpful here: https://github.com/haskell/core-libraries-committee/issues/210#issuecomment-1933827516

In short, there is a single use of `whereFrom` on Hackage by `nothunks` and it now goes via my `wherefrom-compat` compatibility package, so it's insulated from this breaking change.

**Comment by Bodigrim** [comment]
Given that no one voiced in favor of a more conservative approach and given the evidence and impact assessment presented (thanks @TeofilC), I guess we can vote as is.

Dear CLC members, let's vote on the proposal to extend [`GHC.InfoProv.InfoProv`](https://hackage.haskell.org/package/base-4.19.0.0/docs/GHC-InfoProv.html#t:InfoProv) with a new field `ipUnitId :: InfoProv -> String` to expose unit ID (aka package ID) + remove [`GHC.Exts.whereFrom#`](https://hackage.haskell.org/package/base-4.19.0.0/docs/GHC-Exts.html#v:whereFrom-35-) being superseded by [`GHC.InfoProv.whereFrom`](https://hackage.haskell.org/package/base-4.19.0.0/docs/GHC-InfoProv.html#v:whereFrom). 

More specifically, as explained in https://github.com/haskell/core-libraries-committee/issues/214#issuecomment-1924201295, the removal of `whereFrom#` from `GHC.Exts` is caused by the change of the type of the underlying primop. Thus it would be a breaking change anyway, and, given that there are no clients, it seems more prudent to hide `whereFrom#` from `base` altogether. It remains available through `ghc-prim` if one really needs it. 

The change is implemented (as a part of wider refactoring) in https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11341.

@tomjaguarpaw @mixphix @hasufell @velveteer @angerman @parsonsmatt 

----

+1 from me.

**Comment by parsonsmatt** [comment]
+1

**Comment by tomjaguarpaw** [comment]
+1

**Comment by angerman** [comment]
+1 🤞even though I'm a bit concerned about potential non-public churn still. At least [wherefrom-compat](https://hackage.haskell.org/package/wherefrom-compat) is there. Let's see if I'll regret this 😬

**Comment by Bodigrim** [comment]
@mixphix @hasufell @velveteer just a gentle reminder to vote.

**Comment by velveteer** [comment]
+1

**Comment by hasufell** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, that's enough votes to approve.
