### ISSUE TITLE
 Remove `GHC.Desugar`

### ISSUE THREAD

**Issue by bgamari** [haskell/core-libraries-committee#216]
The `GHC.Desugar` module is used by GHC in desugaring arrow syntax and `ANN` pragmas and needn't be exposed from `base`. I propose that we remove it as there are no uses on Hackage beyond those that blindly reexport `base`.

**Comment by hasufell** [comment]
hackage is not the only consumer of GHC and base. It's just an indicator. I'll vote only yes if there's a deprecation period.

**Comment by bgamari** [comment]
I am in principle not opposed to a deprecation period. However, I'd prefer it to be relatively short (e.g. one release). Does this sound reasonable?

**Comment by parsonsmatt** [comment]
Can we backport the deprecation notice?

A one release deprecation policy, if put in place today, would take effect with GHC 9.10 with a warning (estimated ~April 2024) and fully removed in GHC 9.12 (estimated ~October 2024). I don't think this gives sufficient time for industry users to adapt. If I recall right, Angerman's codebase is still on GHC 8, and they're running into bugs and issues trying to get on GHC 9.4.7. GHC 9.4.1 was released August 2022 and evidently still is not suitable for their project. GHC 8.10 was released in March 2020, so their company project is 3.5 years old.

A three release deprecation policy gives us a warning in April '24, and then an estimated removal in October '25. That *feels* like enough notice, especially if upgrading GHC major versions is substantially easier that a larger codebase keep up more easily. But it also delays the hiding for two years from this date.

For this case, since there do appear to be *very* few users, I think it'd be sufficient to put a `DEPRECATION` notice on the module, and backport a release to `base` (and maybe GHC? GHC 8.10.8? not sure the best way to get this out to folks) that warns folks that it will be removed/moved and give them a link to an issue to track the removal if they need to discuss a use-case. This allows us to warn folks who are on early compiler versions + gather feedback + execute the removal more quickly, which to me feels like the best of both worlds.

**Comment by bgamari** [comment]
While we have not routinely backported deprecations in the past, this is in principle something we could do.

**Comment by hasufell** [comment]
> While we have not routinely backported deprecations in the past, this is in principle something we could do.

I quite like the idea, but I'm starting to get anxious about the "-Werror" faction :sweat_smile:

**Comment by Bodigrim** [comment]
I think deprecating in GHC 9.10 and removing GHC 9.12 is a sound strategy. Any objections / opinions? @bgamari?

**Comment by tomjaguarpaw** [comment]
I think stuff that morally doesn't belong in `base` should have deprecation notices attached and big warnings in the docs that there are more appropriate places to import it from. *New* such stuff should not be put in`base` in the first place.  I'm less keen to *remove* such stuff that's already exposed from *base*` without a long deprecation cycle. I like @parsonsmatt's suggestion.

**Comment by Bodigrim** [comment]
I really-really have hard time imagining anyone using `GHC.Desugar` at all, I think there are better applications for our zeal than an elaborate deprecation schema for it.

GHC 9.10 fork date is looming and it would be nice to take an action before it. Shall we just mark the module as deprecated for now and see how it goes?

**Comment by tomjaguarpaw** [comment]
Yes, I suggest we deprecate it. However, that may cause problems at its use site in GHC.

**Comment by parsonsmatt** [comment]
Looking at the module in question: yeah I think deprecation in 9.10 and removal in 9.12 is fine.

**Comment by bgamari** [comment]
> I think deprecating in GHC 9.10 and removing GHC 9.12 is a sound strategy. Any objections / opinions? @bgamari?

This sounds fine to me. I can execute.

**Comment by bgamari** [comment]
See [!12074](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/12074) for implementation

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to deprecate [`GHC.Desugar`](https://hackage.haskell.org/package/base-4.19.0.0/docs/GHC-Desugar.html) in GHC 9.10 / base-4.20 and remove in GHC 9.12 / base-4.21. There does not seem to be any conscious users of this module (and it's hard to suggest a reasonable use case), but it is re-exported for completeness by two alternative preludes (`rebase` and `rerebase`) + `base-orphans` provides a compatibility shim for `AnnotationWrapper` instances (which are unused anywhere else). You can check the full list of affected packages here: https://hackage-search.serokell.io/?q=%5Eimport.*GHC.Desugar

@tomjaguarpaw @hasufell @mixphix @angerman @parsonsmatt @velveteer 

----

+1 from me, seems like an easy win to scrap cryptic stuff from `base` API.

**Comment by tomjaguarpaw** [comment]
+1

**Comment by velveteer** [comment]
+1

**Comment by angerman** [comment]
+1

**Comment by hasufell** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, that's enough votes to approve.

**Comment by adamgundry** [comment]
I've opened https://gitlab.haskell.org/ghc/ghc/-/issues/25112 to track this on the GHC side.
