### ISSUE TITLE
Add new RTS options introduced by eras profiling to GHC.RTS.Flags 

### ISSUE THREAD

**Issue by mpickering** [haskell/core-libraries-committee#254]
GHC MR: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11917

In [GHC MR !11903](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11903) several new RTS flags were added to the compiler. 

* `-he` profiling mode
* `-he` profiling selector
* `--automatic-era-increment`

Therefore we should also modify GHC.RTS.Flags in the same manner so that users can query whether this option is set from their programs, and keep GHC.RTS.Flags up to date with the implemented RTS flags.

**Comment by tomjaguarpaw** [comment]
For reference, this is similar to: https://github.com/haskell/core-libraries-committee/issues/243

**Comment by Bodigrim** [comment]
Since this is very similar to #243 which we've just approved, I don't see much point to wait with a vote. If anything, we definitely want #243 and this land in the same release to bundle changes. 

Dear CLC members, let's vote on the proposal to extend `GHC.RTS.Flags` to reflect [recently added RTS flags for era profiling](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11903). The MR is available at https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11917 and boils down to extending `data DoHeapProfile` with a new constructor `HeapByEra`  and extending `data ProfFlags` with two more fields: `automaticEraIncrement :: Bool` and `eraSelector :: Word`.

@tomjaguarpaw @mixphix @hasufell @velveteer @angerman @parsonsmatt

----

+1 from me.

**Comment by angerman** [comment]
+1

**Comment by velveteer** [comment]
Definitely +1

**Comment by tomjaguarpaw** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, that's enough votes to approve.
