### ISSUE TITLE
Alt as a superclass of Alternative in base

### ISSUE THREAD

**Issue by NorfairKing** [haskell/core-libraries-committee#272]
Let's get Alt as a superclass of Alternative in base.

With Alternative (Either String) being dropped in `lts-22.22`, I find myself reaching for Alt:

https://hackage.haskell.org/package/semigroupoids-6.0.1/docs/Data-Functor-Alt.html

Motivation:

`Either e` can be an `Alt` but cannot be an `Alternative` because there is no way to implement `empty`.
This means we cannot use `<|>`, `some`, `many`, or `optional` on `Either e` eventhough there is a sensible implementation of `<|>` for `Either e`.

**Comment by tomjaguarpaw** [comment]
Just to be clear, there are two parts to your proposal, right?

1. Get `Alt` into `base`
2. Make it a superclass of `Alternative`

**Comment by hasufell** [comment]
Just a note: Adding superclasses can cause disruption to alternative Preludes.

**Comment by NorfairKing** [comment]
@tomjaguarpaw Yes, but I recommend not to do it separately because that could cause extra breakage.

However, as @hasufell points out: Anyone who defines `Alt` themselves might have their code broken even if nothing else breaks.

Here's a more concrete proposal in only one step:



* We define `Alt` in a module `Control.Alt` which is not exposed in `Prelude`:
```
module Control.Alt where
class Alt f where
  (<|>) :: f a -> f a -> f a
  many :: f a -> f a
  some :: f a -> f a
optional :: f a -> f (Maybe a)
```
* We remove `(<|>)`, `many`, and `some` from `Alternative` and have them only exist in `Alt`.
* We change the definition of `Alternative` to 
```
class (Applicative f, Alt f) => Alternative f
```
  
This only breaks:
* `instance Alternative` implementations
* Alternative `Alt` definitions


Alternatively (pun not intended, this time), we could use a multi-step migration plan with less breakage every time, but warnings/breakage 3 times.

**Comment by thielema** [comment]
On Wed, 5 Jun 2024, Tom Sydney Kerckhove wrote:

> @tomjaguarpaw Yes, but I recommend not to do it separately because that 
> could cause extra breakage.
> 
> However, as @hasufell points out: Anyone who defines Alt themselves 
> might have their code broken even if nothing else breaks.

If you follow the PVP, then you would restrict to a specific minor version 
when importing anonymously and unqualified. Nothing would break.

**Comment by NorfairKing** [comment]
> `base` already contains `newtype Alt f x = Alt {getAlt :: f x}` in `Data.Monoid` setting `(<>) = (<|>)`. Perhaps there is a different solution here that involves an additional superclass constraint on `instance Alternative (Either e)`?

Oh then `Alt` isn't a good name.

There's no way to implement `Alternative (Either e)`. You can have `Alternative (Either String)` with `empty = Left ""` but that doesn't really help.
You could have `Monoid e => Alternative (Either e)` but that has the same problem.
The `empty` is incidental complexity for this use-case.


> ...which is a significant breakage, similar in scope to Applicative-Monad and Semigroup-Monoid proposals.

Yes, a bit less because the superclass I propose here isn't in base yet, but indeed.
Perhaps some strategies from that process could be re-used to avoid breakage but I'm not quite familiar with how.

> Could you possibly elaborate the motivation a bit more? Currently you use Alt from semigroupoids, fair enough. Why do you want it a) to be in base, b) to be a superclass of Alternative?

I currently don't use `semigroupoids` because I don't want to incur the very significant extra dependency tree.
I want an `Alt` because I want to use functions like `optional`, `some`, `many`, but types like `Either e` or `Validation (NonEmpty e)` can't have an `empty` implementation so they cannot be an `Alternative`. 
@ocharles also noted this a few years ago.

I consider this proposal a strict improvement, but if it is rejected (which would be fair because the breakage is significant), then I need to implement my own `optional` every time and that's just quite ugly.

**Comment by Bodigrim** [comment]
> I currently don't use `semigroupoids` because I don't want to incur the very significant extra dependency tree.

Would it be good enough if `class Alt` is extracted into a standalone lightweight package?

Are there reasons (beyond aesthetical) to make `Alt` a superclass of `Alternative`?

**Comment by tbidne** [comment]
Note that this:

> We remove `(<|>)`, `many`, and `some` from `Alternative` and have them only exist in `Alt`.

Will break people who import those explicitly under the class name:

```haskell
import Control.Applicative (Alternative ((<|>)) -- now an error
```

```
src/Usage.hs:6:13: error: [GHC-10237]
    In the import of ‘Control.Applicative’:
      an item called ‘Alternative’ is exported, but it does not export any children
      (constructors, class methods or field names) called ‘(<|>)’.
```

That's not to say there isn't a good idea here, just wanted to point this out.

**Comment by meooow25** [comment]
> With Alternative (Either String) being dropped in `lts-22.22`...

What does this mean?

> This means we cannot use `<|>`, `some`, `many`, or `optional` on `Either e`

* `<|>`: We can use `<>`
* `some`, `many`: I'm curious about the situation where you want to use this. They diverge on `Right`.
* `optional`: Again, curious about where this is used. An `Either e (Maybe a)` is a slightly odd thing to have.

**Comment by NorfairKing** [comment]
> Would it be good enough if class Alt is extracted into a standalone lightweight package?
>
> Are there reasons (beyond aesthetical) to make Alt a superclass of Alternative?

I'm not sure how to answer this.
I guess this was the case with semigroups before `Semigroup` was a superclass of `Monoid` as well?

> Note that this:
> 
> > We remove `(<|>)`, `many`, and `some` from `Alternative` and have them only exist in `Alt`.
> 
> Will break people who import those explicitly under the class name:
> 
> ```haskell
> import Control.Applicative (Alternative ((<|>)) -- now an error
> ```
> 
> ```
> src/Usage.hs:6:13: error: [GHC-10237]
>     In the import of ‘Control.Applicative’:
>       an item called ‘Alternative’ is exported, but it does not export any children
>       (constructors, class methods or field names) called ‘(<|>)’.
> ```
> 
> That's not to say there isn't a good idea here, just wanted to point this out.
> 
> Edit: This will of course also break imports like `import Control.Applicative (Alternative (..))`, expecting `(<|>)` to be in scope.


@tbidne Good point!

> > With Alternative (Either String) being dropped in lts-22.22...
>
> What does this mean?

Somewhere deep in the dependency tree, that was an orphan instance that (correctly) got removed.

> optional: Again, curious about where this is used. An Either e (Maybe a) is a slightly odd thing to have.

Fair. I guess the example of `Validation (NonEmpty e)` would be more fitting.
(I have this use-case in [centjes](https://github.com/NorfairKing/centjes))



I also just realised that the type of `some` should be `some :: f a -> f (NonEmpty a)`.

**Comment by AshleyYakeley** [comment]
Is it fair to say that `Alt` is to `Alternative` as `Semigroup` is to `Monoid`?

If so, should `Alt` be a subclass of `Applicative` (instead of just `Functor`)?

**Comment by AshleyYakeley** [comment]
Also if we need to come up with a new name, maybe `Semialternative`?

**Comment by ekmett** [comment]
> Is it fair to say that `Alt` is to `Alternative` as `Semigroup` is to `Monoid`?
> 
> If so, should `Alt` be a subclass of `Applicative` (instead of just `Functor`)?

The corresponding class for `Applicative` is `Apply`. For `Monad` is `Bind`. Both of those could be cleanly bikeshedded to `Semiapplicative` and `Semimonad`, (removing pure/return in the process, but at a hammerblow to what is definable in terms of what causing some serious hand-wringing during adoption, in which case that would suggest `Alt` would be `Semialternative`.

**Comment by AshleyYakeley** [comment]
Wait, these are two completely different monoids we're turning into semigroups by removing the identity, right?

1. We remove `pure`/`return` from `Applicative` and `Monad`, to get `Apply` and `Bind`.
2. We remove `empty` from `Alternative` and `MonadPlus` to get `Alt` and some undefined class.

**Comment by endgame** [comment]
> I'm wondering if perhaps we should also bring in `Pointed` and `Apply`, because there are many things that are `(<*>)`-able without having a sensible `pure`.

IMHO, `Pointed` is to `Applicative` what `Default` is to `Monoid`: it has very little meaning unless there's additional structure. And then you have the usual problems that come with law-only subclasses (either that type inference doesn't infer the constraint that implies the law you actually want, or you define a plethora of new names for the same thing).

I think that instead of bringing more things into `base`, it would be better to find a way to inject intermediate classes that not everyone is going to care about. Ideally, this would let you say "all `Applicative`s are `Alt`s" without making the entire ecosystem declare instances for every intermediate class, or doing an AMP-style migration every time a new useful intermediate class is discovered. That would solve the `Alt` situation here, as well as give us a good interface for niche classes like `InverseSemigroup` (that sit between `Semigroup` and `Group` but aren't of interest to everybody).

**Comment by phadej** [comment]
> Now our familiar type classes are mere synonyms for multiple constraints. This particular setup leaves no `"instance" Alternative (Either e)`, but only for lack of `Empty`.

as @endgame said

> And then you have the usual problems that come with law-only subclasses (either that type inference doesn't infer the constraint that implies the law you actually want, or you define a plethora of new names for the same thing).

**Comment by phadej** [comment]
> If so, should `Alt` be a subclass of `Applicative` (instead of just `Functor`)?

No. `Alt` has `many` which is not definable without `pure`. In regexp-terms `Alternative` not only adds an union&empty but also a Kleene-star.

**Comment by phadej** [comment]
@mixphix then I'd say that

```haskell
type Monad f = (Inject f, Bind f)
```

serve no purpose either, if 

```haskell
type CommutativeMonoid = Monoid
```

doesn't. The class aliases have exactly the same problems in both cases.

**Comment by phadej** [comment]
@mixphix it's easier to consider

```haskell
type Applicative f = (Inject f, Apply f)
```

here `Applicative f` is an empty dictionary, "we promise" that `Applicative` laws (relating `inject` and `<*>` hold).

**Comment by L0neGamer** [comment]
The laws that define typeclasses are part of what makes them useful, and if you can't guarantee that the parts of the type class match the laws then there's not much point in them.

Separating out pure and <*> from Applicative results in a lawless combination of operators, and you can't enforce lawfulness of the super classes in the same way. 

I think this wider ranging topic isn't too useful here right now, anyway; it might be a route to travel in time but we're discussing Alt, Alternative and such.

**Comment by Jashweii** [comment]
I think this is a Haskell problem though not exclusively, e.g. consider structs with many fields in other languages, when most things using them only need a few at a time. But you don't want a plethora of names for each or to keep converting between them. I do think there should ultimately be some sort of language solution, e.g. if you could specify a class constraint/instance for a subset of methods, like how row constraints generally solve that struct problem. In the mean time it's best to consider the library solution on a case by case basis. E.g. I would be surprised if we got Alt before Apply or breaking up Num.

In places where there's a function depending on e.g. Applicative that can be lowered to some new superclass like Pointed or Apply, it's rare that said function itself depends on the laws holding. Sometimes when the laws don't hold, the concept the class represents itself becomes very nebulous. It's not always a matter of laws, e.g. consider ``Monoid a => Applicative (Const a)``, where ``Semigroup a => Apply (Const a)`` is basically the same thing, it's just a lighter constraint on individual methods. For cases where extra laws are wanted, there's a solution other than class aliases - have the class as something the user must opt-in to as an assertion of meeting the laws. I don't agree on the semigroupoids cases though, they still have meaningful laws, you are just dropping an identity.

It's probably not a use everyone is interested in but I quite like being able to reduce the names in scope by preferring to use class methods like mempty etc, instead of needing X.empty, Y.empty, Z.empty. But this sometimes adds unwanted constraints.

**Comment by ekmett** [comment]
@mixphix I can build lots of types that have 'Inject' and '>>=' that aren't compatible. They are damn near useless. Similarly, a pointed semigroup is not a monoid. Laws that only come into existence when you magically get two instances to rub together are a hot mess. You lose the vocabulary for ever expressing the more granular cases where you want those laws not to hold, and users pick up the arcane burden of reasoning case by case through the instances in the hopes that all the implied extra laws do hold. Typeclasses express a mixture of sorts (types), operations and laws about those operations.

Your complete distaste for that third part of that equation doesn't mean that they aren't necessary to do any reasoning about code that uses the associated operations without going down to reasoning through instance by instance over instances that haven't even been written yet.

"Commutative" as a constraint is just a law-only class and yes, inference for it sucks, but if you want to express that a method requires that "additional constraint you have to satisfy" is doing real work, by ensuring that you can see that that additional constraint really is necessary to e.g. fold correctly over mobiles or allow faster fork-join workstealing to sum over arrays without carefully treeing up the result, using the original order, or to extract the contents from a `Bag` without a source of randomness.

Anyways, I just wanted to express a very very strong negative reaction to your proposed scheme. It has been proposed before, heck, much to my chagrin, scalaz even used it at one point in time! 

One of the things I love about Haskell is the ability to reason through my code by laws using the instances at hand and not case by case. This would destroy the very soul of the language for me.

**Comment by blamario** [comment]
@mixphix, @phadej: The reason laws-only classes like `Commutative` matter is because sometimes their laws matter. As  you go from magma to semigroup to commutative semigroup, the additional laws you can count on mean that you gain more freedom to manipulate the expressions.
An expression like `a <> (b <> a) <> c` is a tree if we're dealing with a magma, but becomes a list (aka free monoid) `a <> b <> a <> c` if it's a semigroup, and if it's also commutative we can rearrange it to a multiset (free *commutative* monoid) `a <> a <> b <> c`. If it's also idempotent we can replace the multiset with a plain set. Every step in this chain can substantially simplify the container data structure and improve its performance.

**Comment by Jashweii** [comment]
Re. the partial constraint/instance language solution I meant earlier, it would be strictly less flexible than manually converting everything to single method classes (in which superclass constraints are omitted). Where classes are broken up, normally the case is:
- The maintainer has laws in mind for individual methods (usually) e.g. `mappend` is associative
- Existing overall laws (if they aren't moved into a law class) apply when they type-check (e.g. ``instance Mempty (Maybe a)``)
- Instances for certain subsets of methods are bad ideas (e.g. `mempty` and unconditionally never `mappend`)
I think `Nothing :: Maybe a` is an example of a situation where it makes sense to have `mempty` and not `mappend` *circumstantially, due to the choice of type variable* - it's the same `mempty` that would be a unit for `mappend`, if only `Semigroup a` held.

They don't solve the law class issue, and you can't retroactively introduce law classes for lighter laws.
They don't address adapting unrelated classes.
Both of those probably need known-to-be unmet constraints and backtracking (or something like liquid haskell for laws).
Or something uglier like "declare instance Y for all instance X not depended on by this package". If only used in one or two places then a newtype wrapper is fine for this (would benefit from local data types though).

Nonetheless I think some classes are grautitous and don't have an "obvious" break up that makes everyone happy without being extremely granular (e.g. Num or Lattice), and I also find the semigroupoid classes useful.

**Comment by NorfairKing** [comment]
Bringing this conversation back on topic: what's the process from here for getting this considered by the CLC?

**Comment by tomjaguarpaw** [comment]
The process is documented here: https://github.com/haskell/core-libraries-committee/blob/main/PROPOSALS.md

So I guess we are waiting for stage 2 to occur.

**Comment by Bodigrim** [comment]
@NorfairKing if you are satisfied (and/or fed up ;) with the preliminary discussion above, would you be happy to refine the proposal, spelling out which specific changes (modules / functions / classes / other entities) to `base` and `semigroupoids` are proposed?

**Comment by NorfairKing** [comment]
@Bodigrim I'm not sure this is worth it at all (because of the breakage) and I can't tell whether this has any chance of being accepted.
If, some day, we can make changes like this without breaking the entire ecosystem, I'll have another look.

**Comment by nh2** [comment]
Could anybody link the GHC/base changelog entry where the removal of this instance was pointed out?

**Comment by Bodigrim** [comment]
> So this might be an acidentally undocumented big breakage.

Yes, and difficult to track as well :(

**Comment by TeofilC** [comment]
@Profpatsch If you are keen on this change, it would be great if you made a new proposal for it.

I think the CLC is a lot more hesitant to accept large breaking changes than it might've been when those other changes happened. Although my feeling is that this is a consequence of how painful large breaking changes can be. If we can alleviate the pain then I think people might be more willing. (eg, better tooling, volunteers to help resolve breakage, etc)

**Comment by tomjaguarpaw** [comment]
There's another factor in play, that makes the Alt/Alternative proposal different from the Applicative/Monad proposal: back 10 or so years ago, just before the AMP was enacted, you would have been very hard pressed to find a `Monad` instance where there wasn't also an `Applicative` instance, because `Applicative` is widely useful! `Alt` simply isn't as widely useful, even by the metric of `Alternative` (which itself is used much less than `Applicative` or `Monad`). It simply hasn't become that useful in practice.
