### ISSUE TITLE
What is the difference between dormant and abandoned labels?

### ISSUE THREAD

**Issue by phadej** [haskell/core-libraries-committee#279]
Seems to be quite the same
- Abandoned: abandoned by the proposer (no show)
- Dormant: hibernated by the proposer or committee

https://github.com/haskell/core-libraries-committee/blob/main/PROPOSALS.md#proposal-lifecycle only mentions abandoned.

(there is a slight difference in abandoning by no-show, and abandoning for time being actively: hibernating; but does it matter?)

**Comment by Bodigrim** [comment]
> there is a slight difference in abandoning by no-show, and abandoning for time being actively: hibernating; 

Correct. 

> but does it matter?

Not much. Hibernated proposals sometimes depend on a third party to unblock them, while abandoned proposals can potentially be reopened at will, as soon as someone volunteers to substitute for the proposer.

**Comment by phadej** [comment]
> Hibernated proposals sometimes depend on a third party to unblock them

So when they don't depend on third party, they are the same as abandoned, and when they do they are *blocked* (on 3rd party)?

**Comment by Bodigrim** [comment]
Legally speaking, a proposal is never blocked by third parties, because a proposer retains an ultimate right to demand a vote. (The vote is likely to be negative, and we generally strive to avoid such experience, but...)

"Dormant" is often "blocked" by gaining more experience with / gathering more arguments pro et contra. Like, if an addition does not look harmful, but also is not convincingly strong, we may recommend to hibernate the proposal so that we do not spoil it for future by premature decision.

All in all, there is little procedural difference between "abandoned" and "dormant"; both categories can in principle be revived by a willing volunteer.
