### ISSUE TITLE
Add a MonadFail instance for Either

### ISSUE THREAD

**Issue by treeowl** [haskell/core-libraries-committee#28]
There are basically three reasonable options:

```haskell
-- Commit to String
instance e ~ String => MonadFail (Either e) where
  fail = Left

-- Commit to IsString
instance IsString e => MonadFail (Either e) where
  fail = Left . fromString

-- Don't commit
instance MonadFail (Either String) where
  fail = Left
```

I'd personally lean toward `IsString`, but I don't feel strongly about it.

**Comment by Bodigrim** [comment]
The second option is appealing, but I'm a bit worried that many parser libraries provide `instance IsString` (which is more like IsCoString ;). Should not be too much of a problem OTOH...

**Comment by gbaz** [comment]
prior discussion (including prior rejection): https://gitlab.haskell.org/ghc/ghc/-/issues/12160

**Comment by tomjaguarpaw** [comment]
I'm pretty wary of making code that didn't previously compile start compiling, when it is by the mechanism of enabling implicit behaviours not clearly specified in the code. Currently if I write `do { Pat v <- e; ... }` and `Pat`'s type has other constructors then I will helpfully get an error message

```
No instance for (MonadFail (Either String))
```

Subsequent to this proposal being enacted I would get a run time error. I'm programming Haskell, I never want a run time error if I can avoid it!

Now, one might object that I'm just opposed `MonadFail` in general. Yes, I suppose I am. I don't like `MonadFail` and I think we should work hard to find something better. I especially don't think we should be encouraging its use by adding new instances to base libraries.

**Comment by treeowl** [comment]
@tomjaguarpaw , where's the run-time error? The current situation is rather awkward, because `Either String` seems to be the most basic `MonadFail` in the way `(->) e` is the most basic `MonadReader e`. Yes, `MonadFail` is fairly ad hoc, but it has a useful law and it saves a lot of horizontal space.

**Comment by tomjaguarpaw** [comment]
> where's the run-time error?

I mean a `Left` that I didn't expect.

**Comment by Kleidukos** [comment]
I agree with Tom in the case against the use of `MonadFail`. This is akin to beating a dead horse.

@treeowl  I seem to remember you and Edward were opposed to it, at the time. What has changed?

**Comment by Bodigrim** [comment]
> Now, one might object that I'm just opposed `MonadFail` in general. Yes, I suppose I am. I don't like `MonadFail` and I think we should work hard to find something better. I especially don't think we should be encouraging its use by adding new instances to base libraries.

And yet having `MonadFail Maybe`, but not `MonadFail (Either String)` just encourages people to use the former, which is much worse in the case of non-exhaustive patterns. 

I don't think that `MonadFail` is evil: it's just a type class. Indeed, GHC desugaring of non-exhaustive pattern-matches is questionable and I'm far from happy with it, but let's separate concerns.

**Comment by tomjaguarpaw** [comment]
> it's just a type class ... let's separate concerns

On the contrary, it is deeply baked in to an important aspect of Haskell syntax. If it were just a type class then @treeowl could define `MyMonadFail` with all the instances he likes and go on his way. The reason he is asking for this change is exactly *because* it is more than just a type class. The concerns of this type class and GHC desugaring of non-exhaustive pattern-matches *cannot* be separated!

**Comment by treeowl** [comment]
@Kleidukos you're right; I was opposed. I'm not exactly sure why. Probably fear of commitment. The question of the appropriate superclass is thorny. `IsString` is definitely overkill; as was discussed once upon a time, something more like the old `Error` class would be a better fit.

**Comment by Kleidukos** [comment]
@treeowl Thank you. :) 

As a teacher, `MonadFail` is fairly hard to teach without involving some hand-waving and magic, and I have found students much more receptive to the concept of transformers, even in their MTL form. `fail` is sometimes seen as akin to `error` and I think it's a shame.
By "hard to teach" I mean that it is simple to apprehend but complexity has to live somewhere and since up-front costs aren't paid immediately, we find them later. 

Subsequent question:  Shouldn't we invest our efforts in teaching more structured practices for error reporting? I'd rather go with [hackage.haskell.org/package/validation-selective](validation-selective) and [ExceptT](https://hackage.haskell.org/package/mtl-2.2.2/docs/Control-Monad-Except.html#t:ExceptT) (as well as `MonadError`) for a very large portion of the usecases `MonadFail` is used for.

**Comment by treeowl** [comment]
`MonadFail` serves two main purposes that I know of:

1. `do` and monad comprehension desugaring.
2. A universally available and simple way to produce an exception in `IO` or another `MonadIO` instance.

Why does (2) matter? When you're writing code (especially in early stages) you may not have a plan for exactly what to do about specific exceptions yet, but know that you want them to be in `IO`. It's much better to start out with `liftIO . fail` than to shove `error` in wherever and hope you can ever get it back out.

**Comment by Kleidukos** [comment]
> When you're writing code (especially in early stages) you may not have a plan for exactly what to do about specific exceptions yet, but know that you want them to be in IO

This sounds like a fundamentally subjective experience.

 > It's much better to start out with liftIO . fail than to shove error in wherever and hope you can ever get it back out.
 
I'll do you one better, we raise more awareness about Monad Transformers by cutting ties with this poor excuse for error handling. 

Just for reference: 

```haskell
-- | @since 4.9.0.0
instance MonadFail Maybe where
    fail _ = Nothing
```
Brings almost no visible benefit compared to using `MaybeT` and I don't feel like trying to find any justification.

The IO instance for MonadFail is really just throwing `SomeException` with `failIO`:

```haskell

-- | @since 4.9.0.0
instance MonadFail IO where
    fail = failIO

failIO :: String -> IO a
failIO s = IO (raiseIO# (mkUserError s))

mkUserError       :: [Char]  -> SomeException
mkUserError str   = toException (userError str)
```

And just like that we've produced three layers of indirection instead of teaching how to properly throw and handle exceptions.

I might be harsh but `MonadFail` was a mistake, it was a shortcut when people didn't care much about structured error handling, and I think we must stop indulging these historical missteps.

**Comment by kozross** [comment]
`MonadFail` is a mistake in its present form. Textual errors are awful from just about any perspective imaginable:

* You can't programmatically handle them in a sensible way (except by forwarding them on); and
* They give _zero_ indication of what could have gone wrong or why without reading the source code of _every use of `fail`_.

There _is_ reason for its primary purpose, namely 'what to do if a pattern match in a `do` fails'. We have `Alternative`'s `empty` for this, which works just fine, and is really how it should have worked from the beginning.

I don't think extending this mistake any further benefits anyone.

**Comment by ekmett** [comment]
There's a fourth option as well

```haskell
class Failing t where
  failing :: String -> t

instance Failing t => MonadFail (Either t) where
   fail = Left . failing
```

with implementations for string types. This would render support for MonadFail for Either about the same level of quality it had access to through the orphan `Error` based code in the `mtl`, possibly with the `mtl`'s Error class adopting such a class as a superclass to ensure consistency.

Now I'm not stuck tying my behavior to that of `IsString`, which I may want to have have another meaning.

That said, this did proposal did come up before. As I recall, @treeowl took the other side of the debate on the libraries thread back then. (Though I have no problem with folks updating their beliefs over time!) I'm still weakly against this instance, but if we do it I'd like it to be the "right" instance.

**Comment by andreasabel** [comment]
I am in principle opposed to promote `MonadFail` any further. 
I currently do not see how the proposed addition would encourage good programming style.
The previous discussion has some examples in https://gitlab.haskell.org/ghc/ghc/-/issues/12160#note_121272, but they do not convince me.  Maybe @treeowl you want to reveal the examples that fuel your proposal.

**Comment by Bodigrim** [comment]
@treeowl do you want to put this forward for a vote?

**Comment by treeowl** [comment]
I'll retract it for now. I don't have great answers to the questions.
