### ISSUE TITLE
Make Debug.Trace.{traceEventIO,traceMarkerIO} faster

### ISSUE THREAD

**Issue by hsyl20** [haskell/core-libraries-committee#291]
Proposal: make `base:Debug.Trace.{traceEventIO,traceMarkerIO}` faster when tracing is disabled by checking if the RTS flag enabling user event tracing is enabled before doing any work with the lazy string argument.

- Ticket: https://gitlab.haskell.org/ghc/ghc/-/issues/17949
- MR: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/13295

**Comment by Bodigrim** [comment]
> Certainly this is a user-facing change to comsumers of `base`, but the implementation of `base:Debug.Trace` now lives inside `ghc-internal:GHC.Internal.Debug.Trace`. So there is not much that needs to be done by the CLC, am I wrong @Bodigrim?

Pretty much everything lives inside `ghc-internal` now. The agreement is that whatever is re-exported from `base` falls under CLC purview, even if the implementation is inside `ghc-internal` / `ghc-prim` / `ghc-bignum`.

**Comment by maralorn** [comment]
Well, base is one of the few packages for which it is totally fine to depend on ghc-internal. Changing RTSFlags wouldn't cause an API changing modification of the new implementation of the functions discussed here, would it?

**Comment by doyougnu** [comment]
> but this ticket wants to use them in base to improve the performance of two functions

There is some miscommunication. This proposal was opened because of the [performance change](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/13295#note_586346). The implementation relies on a new module in `ghc-internal` called `GHC.RTS.Flags.Test`, its sole purpose is a [top level constant](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/13295/diffs#c83dddabd663f5b4266ffb0ae7eb0dc35ef48738_0_28) that detects if the RTS has eventlog support or not, but crucially *this is not added to base*. The new module is exposed in `ghc-internal` but is only used by the `Debug.Trace` implementation which _is still_ re-exported to base. The goal of this proposal is approval for the MR _because_ of the runtime performance changes.

## How does this proposal relate to #289 

It doesn't, the goal is not to move `Debug.Trace` or add flags to base, only alter `Debug.Trace.traceEvent` and `Debug.Trace.traceEventIO`'s implementation. Both are re-exported from `ghc-internal` to base just as before. The newer implementation does not rely on either `GHC.RTS.Flags` or `GHC.Stat` which is what #289 is concerned with. 

Does that make things more clear?

**Comment by Ericson2314** [comment]
Excellent separation of concerns! The CLC is asked to sign off on a change in the performance *contract* (external interface), but the *mechanism* that implements that remains private because it relies on unstable interfaces.

**Comment by hsyl20** [comment]
> Well, base is one of the few packages for which it is totally fine to depend on ghc-internal. Changing RTSFlags wouldn't cause an API changing modification of the new implementation of the functions discussed here, would it?

Yes whatever we decide for RTSFlags shouldn't impact this.

May I ask for a vote on this?

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to make `traceEventIO` / `traceMarkerIO` from `Debug.Trace` faster in case if eventlog profiling has not been enabled. There is no change in API or observed behavior: `traceEventIO` is no-op if eventlog was not enabled (through runtime RTS options), we simply move the check earlier, so that users are free to set up tracing in various parts of their application without paying an ongoing penalty in case of normal execution.

@tomjaguarpaw @mixphix @hasufell @velveteer @parsonsmatt @angerman 

----

+1 from me, IMHO this is most useful.

**Comment by tomjaguarpaw** [comment]
+1

**Comment by hasufell** [comment]
+1

**Comment by velveteer** [comment]
+1

**Comment by angerman** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, that's enough votes to approve.
