### ISSUE TITLE
Permit Semigroup/Monoid instances with only sconcat/mconcat?

### ISSUE THREAD

**Issue by Gabriella439** [haskell/core-libraries-committee#61]
In other words, permit `sconcat` as a minimal definition for `Semigroup` and `mconcat` as a minimal definition for `Monoid`, where `(<>)` has a default implementation of:

```haskell
l <> r = sconcat (l :| [ r ])
```

… and `mempty` has a default implementation of:

```haskell
mempty = mconcat []
```

This would also entail updating the `MINIMAL` pragma for each class to match.

The motivation for this is two-fold:

* to permit what mathematicians call an "unbiased" definition

  c.f. [biased definition](https://ncatlab.org/nlab/show/biased+definition), which is useful in educational/expository materials related to abstract algebra

  Sometimes defining an "unbiased" `Monoid`/`Semigroup` instance purely in terms of `mconcat`/`sconcat` is clearer or more instructive in a certain context 

  For example, the `Monoid` instance for lists is simpler when defining `mconcat` instead of `mempty` / `(<>`):

  ```haskell
  instance Monoid [a] where
      mconcat = concat
  ```

  I don't actually expect the `Monoid` instance for lists to be implemented solely in terms of `mconcat`, but this again would be highly useful for educational material explaining various instances and proofs of their laws when the unbiased version is simpler than the biased version

* to allow `mconcat` / `sconcat` to be the source of truth so that `mempty` / `mconcat` don't diverge and similarly `(<>)` / `sconcat` don't diverge

  There are some `Monoid`s where it is more efficient to implement `sconcat` / `mconcat` directly instead of `(<>)` / `mempty`.  One common example is the `Monoid` instance for any product type with `Monoid`-valued fields.  For example, for Haskell's 2-tuple type, it's more efficient to define `mconcat` directly like this:

  ```haskell
  instance (Monoid a, Monoid b) => Monoid (a, b) where
      mconcat abs = (mconcat (map fst abs), mconcat (map snd abs))
  ```

  … rather than to use the default definition of `mconcat = foldr (<>) mempty` because with the direct definition of `mconcat` you don't need to construct/deconstruct a bunch of intermediate 2-tuples.  (Note: `base` currently does not directly implement `mconcat` for N-tuples, which it should, but that's orthogonal to this proposal)

  This is true not just for N-tuples in `base` but many user-defined record types with `Monoid`-valued fields, like:

  ```haskell
  data Example = Example{ foo :: Bool, bar :: Int }

  instance Monoid Example where
      mconcat examples = Example{ foo = any (map foo examples), bar = sum (map bar examples) }
  ```

  … and if you had to define both `mempty` and `mconcat` for the `Monoid` instance then you run the risk of the two methods diverging (i.e. the behavior of `mempty` not necessarily matching the behavior of `mconcat`).  For example, you might define this invalid `Monoid` instance by accident if you had to supply both `mconcat` and `mempty`:

  ```haskell
  instance Monoid Example where
      mempty = Example{ foo = True, bar = 0 }

      mconcat examples = Example{ foo = any (map foo examples), bar = sum (map bar examples) }
  ```

  Also, more generally, it's a maintenance burden to have to keep both of those definitions in sync when one would suffice.

  Moreover, as noted in https://github.com/haskell/core-libraries-committee/issues/61#issuecomment-1123974821, when `(<>)` / `mempty` are defined in terms of `sconcat` / `mconcat` they can still be just as efficient as if they had been defined directly.

**Comment by Gabriella439** [comment]
I should also mention what the relevant laws would be for instances that only implement `sconcat` / `mconcat`:

```haskell
sconcat (x :| []) = x

-- xss :: Semigroup m => NonEmpty (NonEmpty m)
sconcat (join xss) = sconcat (fmap sconcat xss)

mconcat [ x ] = x

-- xss :: Monoid m => [[m]]
mconcat (join xss) = mconcat (fmap mconcat xss)

mconcat (NonEmpty.toList xs) = sconcat xs
```

From those laws you can derive the traditional identity/associativity laws.  Here's the proof of the right identity law:

```haskell
mempty <> x

= sconcat (mconcat [ ] :| x)

= mconcat [ mconcat [ ], x ]

= mconcat [ mconcat [ ], mconcat [ x ] ]

= mconcat (fmap mconcat [ [ ], [ x ] ])

= mconcat (join [ [ ], [ x ] ])

= mconcat [ x ]

= x
```

… and here's the proof of the associativity law:

```haskell
(x <> y) <> z

= sconcat (sconcat (x :| [ y ]) :| [ z ])

= sconcat (sconcat (x :| [ y ]) :| [ sconcat (z :| [ ]) ])

= sconcat (fmap sconcat ((x :| [ y ]) :| [ z :| [ ] ]))

= sconcat (join ((x :| [ y ]) :| [ z :| [ ] ]))

= sconcat (x :| [ y, z ])

= sconcat (join ((x :| [ ]) :| [ y :| [ z ] ]))

= sconcat (fmap sconcat ((x :| [ ]) :| [ y :| [ z ] ]))

= sconcat (sconcat (x :| [ ]) :| [ sconcat (y :| [ z ]) ])

= sconcat (x :| [ y :| [ z ] ])

= x <> (y <> z)
```

**Comment by Gabriella439** [comment]
@chessai: Could you explain how would this interfere with efficiency?

**Comment by chessai** [comment]
For mempty, you would never want the mconcat [] to not just be some constant.

For append (<>), you would want to stop the nonempty list from materialising.

There are many monoids for which mempty/append are cheap to implement in straightforward ways that don't involve these additional materialisations and indirections.

**Comment by Gabriella439** [comment]
The lists are not materialized when you implement `mempty` and `(<>)` in terms of `mconcat` / `sconcat`.  For example, this module:

```haskell
module Test where

class Monoid' m where
    mconcat' :: [m] -> m

mempty' :: Monoid' m => m
mempty' = mconcat' []

mappend' :: Monoid' m => m -> m -> m
mappend' l r = mconcat' [ l, r ]

instance Monoid' Int where
    mconcat' = sum

example :: Int -> Int
example x = mappend' x 2
```

… generates this core for `example`:

```haskell
example
  = \ x_aEw -> case x_aEw of { I# x1_X1AN -> I# (+# x1_X1AN 2#) }
```

… which doesn't materialize the intermediate list.

**Comment by chessai** [comment]
I suppose this woudn't be too bad if instead of (for eg Semigroup) `MINIMAL sconcat`, it was `MINIMAL (sconcat | (<>))`.

Also, I don't really trust the optimiser at scale. I've had production code performance degrade (which was visible in the core) too many times after refactorings or compiler upgrades. As such, tiny core "benchmarks" aren't really convincing to me.

I think if we do the "one-or-the-other" minimal change, that would be less disruptive (as most define just (<>)/mempty) and provide the same simplicity and flexibility to those who want it.

**Comment by chessai** [comment]
Oh, I think I misunderstood the proposal - I think you are proposing updating the MINIMAL pragmas in the way I just outlined. I thought you were just suggesting moving to sconcat/mconcat alone. Can you clarify which one you mean? If I misinterpreted you, please let me know.

**Comment by Gabriella439** [comment]
Yeah, I meant `MINIMAL (sconcat | (<>))`

**Comment by Gabriella439** [comment]
No worries! 🙂

**Comment by chshersh** [comment]
@Gabriella439 Could you give some examples where it's easier to define `sconcat / mconcat` than `<> / mappend`? I believe it would increase the motivation for this proposal even further 🙂 

I also wonder how this affects GHC error messages for learners and experienced users. Currently, if I just write the instance head as single line `instance Semigroup Foo where` I get a warning:

```
   • No explicit implementation for
        ‘<>’
    • In the instance declaration for ‘Semigroup Foo’
   |
46 | instance Semigroup Foo
   |          ^^^^^^^^^^^^^
```

But if I define something like this:

```haskell
data Foo = Foo

class Semigroup' a where
    (<<>>) :: a -> a -> a
    l <<>> r = sconcat' (l :| [r])

    sconcat' :: NonEmpty a -> a
    sconcat' = foldr1 (<<>>)

instance Semigroup' Foo
```

I don't get a warning with the following set of GHC flags enabled:

```haskell
  ghc-options:         -Wall
                       -Wcompat
                       -Widentities
                       -Wincomplete-uni-patterns
                       -Wincomplete-record-updates
                       -Wredundant-constraints
  if impl(ghc >= 8.2)
    ghc-options:       -fhide-source-paths
  if impl(ghc >= 8.4)
    ghc-options:       -Wmissing-export-lists
                       -Wpartial-fields
  if impl(ghc >= 8.8)
    ghc-options:       -Wmissing-deriving-strategies
  if impl(ghc >= 8.10)
    ghc-options:       -Wunused-packages
  if impl(ghc >= 9.0)
    ghc-options:       -Winvalid-haddock
  if impl(ghc >= 9.2)
    ghc-options:       -Wredundant-bang-patterns
                       -Woperator-whitespace
```

**Comment by Gabriella439** [comment]
Some examples instances using `mconcat` are:

```haskell
instance Monoid [a] where
    mconcat = concat

instance Monoid Any where
    mconcat = coerce or

instance Monoid All where
    mconcat = coerce and

instance Num a => Monoid (Sum a) where
    mconcat = coerce sum

instance Num a => Monoid (Product a) where
    mconcat = coerce product

instance Monoid a => Monoid (Dual a) where
    mconcat = coerce (mconcat . reverse)
```

For your example `Semigroup'` instance you'd also need a `MINIMAL` pragma to get a useful error message

**Comment by phadej** [comment]
In all these examples (`[a]`, `Any`, `All`, `Sum a`, `Product a`, `Dual a`), you also want to define `mempty` (and `<>`) explicitly.
I'm not convinced there is a case where you don't want to define `mempty` explicitly.

It looks like that `mconcat` isn't explicitly defined for all of these, it should be. The member is there to allow more efficient implementations. But that is orthogonal/separate to this proposal.

**Comment by Bodigrim** [comment]
@Gabriella439 could you please extend the proposal with a motivation section? What does this additional flexibility buy us?

**Comment by Gabriella439** [comment]
@Bodigrim: I updated the motivation section

**Comment by Bodigrim** [comment]
I'd like to have a feedback from educators on the proposed change. CC @GrahamHutton, @argumatronic, @chris-martin, @chshersh.

**Comment by chshersh** [comment]
From an educator's perspective, the proposed change doesn't help me to explain `Semigroup` and `Monoid`. I find it easier to explain and understand when you append **two things** instead of **zero or more (potentially infinite number of) things**. Even the example with lists uses `concat` and `concat` is implemented via `++` which appends two lists together.

I haven't seen a single example where `mconcat` is implemented without the usage of `<>` eventually. Using `mconcat` to define `<>` feels to me like using an Excel spreadsheet to find a sum of two numbers — yes, you can do this but there're simpler ways. It goes in the opposite direction of the widespread Haskel approach — creating more complex functions from smaller primitive combinators. If you need to process a single value of type `A`, you don't build a streaming library first to process streams of `A` and then implement all functions to work on `A` as functions on a singleton stream.

Also, in some examples in the motivation section, the performance actually became worse. For example, here:

```haskell
data Example = Example{ foo :: Bool, bar :: Int }

instance Monoid Example where
    mconcat examples = Example{ foo = any (map foo examples), bar = sum (map bar examples) }
```

This approach introduces space leaks as you traverse the same list twice and keep the reference to the entire list in the other field. If `Example` is defined using `StrictData`, a more efficient (and much simpler) implementation of `mconcat` would be just `foldl' (<>) mempty`.

In the end, to write efficient Haskell, you probably almost always want a custom implementation of `mconcat` or `sconcat`. The same goes for `<>`.

I understand the value in having consistency between `scocat / <>` and `mconcat / <>, mempty`. But I feel like adding more checks to libraries that perform property-based testing of typeclasses laws would be a better approach

* https://hackage.haskell.org/package/hedgehog-classes-0.2.5.3/docs/Hedgehog-Classes.html#v:semigroupLaws

<hr>

Overall, I'm not against the proposal. I don't mind it as long as it doesn't break things. It doesn't help me but it doesn't hurt either. I just don't think it's worth the hassle as the benefits don't seem to outweigh the amount of work.

**Comment by Gabriella439** [comment]
@chshersh: Can you clarify what hassle you are referring to?

**Comment by chshersh** [comment]
@Gabriella439 Apologies, _hassle_ was a wrong choice of words. Its meaning is _irritating inconvenience_ (as I just checked and apparently was using the word wrongly my entire life). But I don't see anything irritating or inconvenient in this proposal. I rephrased my last sentence to better clarify what I mean 🙂

**Comment by chris-martin** [comment]
I very much appreciate having multiple minimal-complete choices when writing educational materal.

My favorite example of this is `(<*>)` and `liftA2` -- it is very handy to switch between them and use whichever definition most naturally fits the perspective on Applicative we're talking about at the time. I would look forward to this `Semigroup` change as a new opportunity to introduce unbiased definitions, making up for the unfortunate loss of the `(/=)` method from `Eq`.

I do not find that the presence of an additional minimal definition can present me with any difficulty, because I do not feel any obligation to exhaustively address all of the methods in a class if I don't want to. If we do not wish to deal with `sconcat`, then we simply do not bring it up; all we have to do is observe that `(<>)` is the minimal complete definition that we are choosing to work with at the moment, and that is that. We already have to do this with `Eq`, since we are anticipating losing `(/=)` and have to write material that makes sense both before and after the removal of `(/=)` is inflicted upon the `Eq` class.

**Comment by Ericson2314** [comment]
I agree with @chris-martin. Even if no one ever uses this, the more "always true" default methods (as opposed to the "sometimes true" ones arguably better served by deriving via) serve to better document the laws. I always enjoy reading such default methods even if I am not going to use them. This would be a beautiful addition to both classes. Thank you, @Gabriella439!

**Comment by Bodigrim** [comment]
@Gabriella439 could you please prepare a draft MR, so that we can vote on it?

**Comment by Gabriella439** [comment]
The merge request is up here: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8450

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to add default definitions for `(<>)` in terms of `sconcat` and for `mempty` in terms of `mconcat` as detailed at https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8450/diffs. @tomjaguarpaw @mixphix @emilypi @cgibbard @chessai 

----

+1 from me, I'm convinced by @chris-martin's arguments.

**Comment by chessai** [comment]
+1

**Comment by tomjaguarpaw** [comment]
+1

**Comment by emilypi** [comment]
+1

**Comment by Bodigrim** [comment]
With 5 votes in favor out of 6 possible, the proposal is approved. Thanks all!

**Comment by emilypi** [comment]
+1 retroactively ;)

**Comment by chshersh** [comment]
I'm trying to summarise the state of this proposal as part of my volunteering effort to track the progress of all `approved` CLC proposals.

| Field | Value |
|---|---|
| **Authors**            |  @Gabriella439   |
| **Status**             |  merged  |
| **`base` version**     | `4.18.0.0`  |
| **Merge Request (MR)** | https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8450 |
| **Blocked by**         | nothing |
| **CHANGELOG entry**    | present  |
| **Migration guide**    |  not needed |

[changelog]: https://gitlab.haskell.org/ghc/ghc/-/blob/ghc-9.6/libraries/base/changelog.md

Please, let me know if you find any mistakes 🙂
