### ISSUE TITLE
Add `applyWhen`

### ISSUE THREAD

**Issue by schuelermine** [haskell/core-libraries-committee#71]
**This is a proposal split from #66**

### Suggestion

I suggest to add the following function to `Data.Function`:

```hs
applyWhen :: forall a. Bool -> (a -> a) -> a -> a
applyWhen True f x = f x
applyWhen _    _ x = x
```

This function is taken from `ghc`’s `GHC.Utils.Misc`.

### Variations

Additionally, an inverse could be added:

```hs
applyUnless :: forall a. Bool -> (a -> a) -> a -> a
applyUnless = applyWhen . not
```

**Comment by Bodigrim** [comment]
My concern is that `applyWhen` is just `Data.Bool.bool id`, however admittedly the order of arguments of `bool` is always so confusing.

**Comment by JakobBruenker** [comment]
It's not just the argument order, the naming also makes it much more obvious what `applyWhen` means compared to `bool id`, I think.

When I can't use `applyWhen` I much prefer using an `if`-expression over `bool id` for that reason, so in my opinion `bool id` isn't actually a realistic alternative to `applyWhen`.

**Comment by Bodigrim** [comment]
@schuelermine are you happy to trigger a vote? I suggest voting for `applyWhen` and `applyUnless` separately.

**Comment by schuelermine** [comment]
Yeah, that seems reasonable. I don’t see much to vary here except argument order, which seem OK this way as an alternative to `bool`.

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposals to add `applyWhen` and `applyUnless` to `Data.Function`. @tomjaguarpaw @chessai @mixphix @emilypi @cgibbard 

----

+1 for `applyWhen`, it's a handy pattern.
-1 for `applyUnless`, it's not that difficult and more clear to write `applyWhen . not`.

**Comment by mixphix** [comment]
+1 to both. We already have `unless`, and I wouldn't want to remove it, or `applyUnless` if the latter were already in `base`, so I think it deserves a place here.

**Comment by emilypi** [comment]
-1 on both.

**Comment by tomjaguarpaw** [comment]
-1 on both

----

This don't pass the Fairbairn threshold for me.

**Comment by Bodigrim** [comment]
@cgibbard @chessai a gentle reminder to vote.

**Comment by chessai** [comment]
+1 on applyWhen

-1 on applyUnless (In real code I prefer (when . not))

**Comment by Bodigrim** [comment]
@cgibbard a reminder to vote.

**Comment by Bodigrim** [comment]
There are 4 votes out of 6 against `applyUnless`, so this one is rejected.
There are 4 votes out of 6 in favor of `applyWhen`, so this one is approved.

@schuelermine please raise a GHC MR for `applyWhen`.

**Comment by nomeata** [comment]
Hmm, I wonder if two independent tallys for a proposal with multiple variants is the right approach. There are four possible outcomes, yet everyone only got to express their most favorite, but not how they assess the other outcomes. For all the people who said ±1 to both it is not clear what they think of a mixed outcome. The opinion ”add either both or none, because it is surprising and inconsistent if it doesn't mirror the well-known when/unless pair” could not be expressed.

Or put differently, I see a 2-2-2 tie between three options (well, depending on what @cgibbard thinks about applyUnless…)

I suggest when there are more than two outcomes possible to always ask for ranked voting of all options, so you can pick the Condorcet winner, if there is one.

Or maybe I'm just too nerdy around voting systems :-)

**Comment by schuelermine** [comment]
No, cardinal voting is better :)

**Comment by Bodigrim** [comment]
@nomeata I appreciate your experience, but I find ranked voting impractical under current circumstances. CLC members were asked to vote on the proposals separately, so I do not see the results as ambiguity.

**Comment by schuelermine** [comment]
So should I make a MR?

**Comment by schuelermine** [comment]
I have made a WIP MR (currently w/o test cases): https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8529

**Comment by nomeata** [comment]
> CLC members were asked to vote on the proposals separately

Right, and that is what I am surprised at, as it's not two independent proposals, but more one proposal with a possible add-on variant.

Would we have gotten the same outcome of you first voted on the proposal as a whole (should we do anything?) and only if that gets accepted voted on the variant?

Whoever asks the questions has a lot of power here, and different ways of asking can lead to different results.

But if a majority of the committee indeed prefers this outcome over rejecting both or accepting both (which of course I can't tell, only the committee can), then all is well, so if noone on the committee minds, I'll let it be.

**Comment by tomjaguarpaw** [comment]
Although I don't believe the current system has led to any bad decisions, here or elsewhere, I do think it's worth considering improvements to the current system. However, it is a difficult problem. The current system has the benefit that a proposer has to make one very clear proposal (often with an MR) that the committee votes yes or no on. That has a lot of benefits. (Here there were effectively two distinct proposals.) I am also sceptical that we can significantly improve `base` with small individual proposals.

I am more in favour of fewer, larger discussions about the scope and purpose of base in its entirety, for example https://github.com/haskell/core-libraries-committee/issues/70 is getting that way.

**Comment by Bodigrim** [comment]
@nomeata I appreciate your input. This is indeed an authority of a chair to trigger votes, and I exercise my expertise to do it in a practical way. Unfortunately, under current constraints, I don't expect further meta-discussion to be productive; other casts of CLC or other chairs might do things differently.

**Comment by chshersh** [comment]
I'm trying to summarise the state of this proposal as part of my volunteering effort to track the progress of all `approved` CLC proposals.

| Field | Value |
|---|---|
| **Authors**            |  @schuelermine   |
| **Status**             |  merged  |
| **`base` version**     | `4.18.0.0`  |
| **Merge Request (MR)** | https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8529 |
| **Blocked by**         | nothing |
| **CHANGELOG entry**    | present  |
| **Migration guide**    |  not needed |

[changelog]: https://gitlab.haskell.org/ghc/ghc/-/blob/master/libraries/base/changelog.md

Please, let me know if you find any mistakes 🙂  

<hr>

Even though, the initial proposal was about adding two new functions: `applyWhen` and `applyUnless`, only `applyWhen` was approved and implemented. Because of that, the issue has two labels: `approved` and `declined`.

I find it a bit confuse. So since the issue title now says only about `applyWhen`, and this can be seen as the refinement of the original proposal, I'll remove the `declined` label.
